export interface GameDeck {
  id: string;
  name: string;
  description: string;
  symbol: string;
  cards: readonly string[];
}

export const GAME_DECKS = [
  {
    id: "all-sorts",
    name: "All sorts",
    description: "A friendly mix of people, places, objects, and oddities.",
    symbol: "✦",
    cards: [
      "Air fryer",
      "Beyoncé",
      "Big Ben",
      "Bubble wrap",
      "Camping",
      "Chess",
      "Croissant",
      "David Attenborough",
      "Disco ball",
      "Double-decker bus",
      "Espresso martini",
      "FaceTime",
      "Fire alarm",
      "Harry Potter",
      "IKEA",
      "Karaoke",
      "London Underground",
      "Mona Lisa",
      "Netflix",
      "Oxford Street",
      "Passport",
      "Picnic",
      "Roller coaster",
      "Self-checkout",
      "Sherlock Holmes",
      "Sunday roast",
      "Taylor Swift",
      "The Moon",
      "Tooth fairy",
      "Uber",
    ],
  },
  {
    id: "screen-time",
    name: "Screen time",
    description: "Films and television nearly everyone has an opinion about.",
    symbol: "▣",
    cards: [
      "Barbie",
      "Black Mirror",
      "Bridgerton",
      "Breaking Bad",
      "Chicken Run",
      "Doctor Who",
      "Friends",
      "Game of Thrones",
      "Gladiator",
      "Home Alone",
      "Inception",
      "James Bond",
      "Jurassic Park",
      "Love Island",
      "Paddington",
      "Peaky Blinders",
      "Shrek",
      "Spider-Man",
      "Squid Game",
      "Star Wars",
      "Stranger Things",
      "Succession",
      "The Crown",
      "The Lion King",
      "The Office",
      "The Simpsons",
      "Titanic",
      "Toy Story",
      "Wednesday",
      "Wicked",
    ],
  },
  {
    id: "act-it-out",
    name: "Act it out",
    description: "No words needed. Become the thing on the card.",
    symbol: "↝",
    cards: [
      "Applying mascara",
      "Bowling",
      "Brushing your teeth",
      "Changing a nappy",
      "Climbing a ladder",
      "Dodging rain",
      "Doing yoga",
      "Folding a fitted sheet",
      "Hailing a taxi",
      "Ice skating",
      "Making a cocktail",
      "Missing the bus",
      "Opening a stubborn jar",
      "Parallel parking",
      "Playing the drums",
      "Putting up a tent",
      "Riding a horse",
      "Running for a train",
      "Sending a voice note",
      "Sneaking in late",
      "Taking a selfie",
      "Walking a tiny dog",
      "Washing your hair",
      "Winning the lottery",
      "Wrapping a present",
      "Zipping a suitcase",
    ],
  },
  {
    id: "british-bits",
    name: "British bits",
    description: "The deeply familiar, from meal deals to questionable weather.",
    symbol: "☂",
    cards: [
      "A cheeky Nando's",
      "Bank holiday",
      "Biscuit tin",
      "Boris bike",
      "Boxing Day",
      "Builders' tea",
      "Corner shop",
      "Council tax",
      "Cream tea",
      "Greggs",
      "Meal deal",
      "MOT",
      "National Rail",
      "Notting Hill Carnival",
      "Pantomime",
      "Parklife",
      "Pimm's",
      "Queueing",
      "Rain forecast",
      "Sunday roast",
      "The Great British Bake Off",
      "The pub quiz",
      "TV licence",
      "Wetherspoons",
      "Wimbledon",
      "Yorkshire pudding",
    ],
  },
] satisfies readonly GameDeck[];

export function shuffledCards(cards: readonly string[]) {
  const next = [...cards];
  for (let index = next.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [next[index], next[swapIndex]] = [next[swapIndex], next[index]];
  }
  return next;
}
