export type DeckCategory =
  | "mixed"
  | "screen"
  | "music"
  | "geek"
  | "world"
  | "life"
  | "active"
  | "mine";

/** Order here is the order the picker groups them in. */
export const DECK_CATEGORIES: ReadonlyArray<{ id: DeckCategory; label: string }> = [
  { id: "mixed", label: "Mixed bag" },
  { id: "screen", label: "Screen" },
  { id: "geek", label: "Fandom" },
  { id: "music", label: "Music & stage" },
  { id: "world", label: "The world" },
  { id: "life", label: "Everyday life" },
  { id: "active", label: "Get up and move" },
  { id: "mine", label: "Your decks" },
];

export interface GameDeck {
  id: string;
  name: string;
  description: string;
  symbol: string;
  category: DeckCategory;
  cards: readonly string[];
}

export const GAME_DECKS = [
  {
    id: "all-sorts",
    name: "All sorts",
    description: "A friendly mix of people, places, objects, and oddities.",
    symbol: "✦",
    category: "mixed",
    cards: [
      "Air fryer",
      "Beyoncé",
      "Big Ben",
      "Bubble wrap",
      "Camping",
      "Chess",
      "Croissant",
      "David Attenborough",
      "Disco ball",
      "Double-decker bus",
      "Espresso martini",
      "FaceTime",
      "Fire alarm",
      "Harry Potter",
      "IKEA",
      "Karaoke",
      "London Underground",
      "Mona Lisa",
      "Netflix",
      "Oxford Street",
      "Passport",
      "Picnic",
      "Roller coaster",
      "Self-checkout",
      "Sherlock Holmes",
      "Sunday roast",
      "Taylor Swift",
      "The Moon",
      "Tooth fairy",
      "Uber",
    ],
  },
  {
    id: "screen-time",
    name: "Screen time",
    description: "Films and television nearly everyone has an opinion about.",
    symbol: "▣",
    category: "screen",
    cards: [
      "Barbie",
      "Black Mirror",
      "Bridgerton",
      "Breaking Bad",
      "Chicken Run",
      "Doctor Who",
      "Friends",
      "Game of Thrones",
      "Gladiator",
      "Home Alone",
      "Inception",
      "James Bond",
      "Jurassic Park",
      "Love Island",
      "Paddington",
      "Peaky Blinders",
      "Shrek",
      "Spider-Man",
      "Squid Game",
      "Star Wars",
      "Stranger Things",
      "Succession",
      "The Crown",
      "The Lion King",
      "The Office",
      "The Simpsons",
      "Titanic",
      "Toy Story",
      "Wednesday",
      "Wicked",
    ],
  },
  {
    id: "act-it-out",
    name: "Act it out",
    description: "No words needed. Become the thing on the card.",
    symbol: "↝",
    category: "active",
    cards: [
      "Applying mascara",
      "Bowling",
      "Brushing your teeth",
      "Changing a nappy",
      "Climbing a ladder",
      "Dodging rain",
      "Doing yoga",
      "Folding a fitted sheet",
      "Hailing a taxi",
      "Ice skating",
      "Making a cocktail",
      "Missing the bus",
      "Opening a stubborn jar",
      "Parallel parking",
      "Playing the drums",
      "Putting up a tent",
      "Riding a horse",
      "Running for a train",
      "Sending a voice note",
      "Sneaking in late",
      "Taking a selfie",
      "Walking a tiny dog",
      "Washing your hair",
      "Winning the lottery",
      "Wrapping a present",
      "Zipping a suitcase",
    ],
  },
  {
    id: "british-bits",
    name: "British bits",
    description: "The deeply familiar, from meal deals to questionable weather.",
    symbol: "☂",
    category: "life",
    cards: [
      "A cheeky Nando's",
      "Bank holiday",
      "Biscuit tin",
      "Boris bike",
      "Boxing Day",
      "Builders' tea",
      "Corner shop",
      "Council tax",
      "Cream tea",
      "Greggs",
      "Meal deal",
      "MOT",
      "National Rail",
      "Notting Hill Carnival",
      "Pantomime",
      "Parklife",
      "Pimm's",
      "Queueing",
      "Rain forecast",
      "Sunday roast",
      "The Great British Bake Off",
      "The pub quiz",
      "TV licence",
      "Wetherspoons",
      "Wimbledon",
      "Yorkshire pudding",
    ],
  },
  {
    id: "anime",
    name: "Anime & manga",
    description: "Long-running giants, studio classics, and the ones everyone quotes.",
    symbol: "☄",
    category: "geek",
    cards: [
      "Attack on Titan",
      "Astro Boy",
      "Berserk",
      "Bleach",
      "Chainsaw Man",
      "Cowboy Bebop",
      "Death Note",
      "Demon Slayer",
      "Dragon Ball Z",
      "Fullmetal Alchemist",
      "Ghost in the Shell",
      "Howl's Moving Castle",
      "Hunter x Hunter",
      "Jujutsu Kaisen",
      "Kiki's Delivery Service",
      "My Hero Academia",
      "My Neighbour Totoro",
      "Naruto",
      "Neon Genesis Evangelion",
      "One Piece",
      "One Punch Man",
      "Pokémon",
      "Princess Mononoke",
      "Sailor Moon",
      "Spirited Away",
      "Spy x Family",
      "Studio Ghibli",
      "Tokyo Ghoul",
      "Vinland Saga",
      "Your Name",
    ],
  },
  {
    id: "video-games",
    name: "Video games",
    description: "Arcade cabinets to open worlds, and the characters in between.",
    symbol: "◈",
    category: "geek",
    cards: [
      "Among Us",
      "Animal Crossing",
      "Assassin's Creed",
      "Call of Duty",
      "Candy Crush",
      "Counter-Strike",
      "Crash Bandicoot",
      "Cyberpunk 2077",
      "Donkey Kong",
      "Elden Ring",
      "FIFA",
      "Fortnite",
      "Grand Theft Auto",
      "Halo",
      "Lara Croft",
      "League of Legends",
      "Mario Kart",
      "Minecraft",
      "Pac-Man",
      "Roblox",
      "Sonic the Hedgehog",
      "Space Invaders",
      "Street Fighter",
      "Super Mario",
      "Tetris",
      "The Last of Us",
      "The Sims",
      "Wii Sports",
      "World of Warcraft",
      "Zelda",
    ],
  },
  {
    id: "superheroes",
    name: "Capes & villains",
    description: "Comic-book heroes, their nemeses, and the films they carry.",
    symbol: "◊",
    category: "geek",
    cards: [
      "Aquaman",
      "Batman",
      "Black Panther",
      "Black Widow",
      "Captain America",
      "Catwoman",
      "Deadpool",
      "Doctor Strange",
      "Green Lantern",
      "Groot",
      "Harley Quinn",
      "Hulk",
      "Iron Man",
      "Joker",
      "Loki",
      "Magneto",
      "Ms Marvel",
      "Poison Ivy",
      "Robin",
      "Scarlet Witch",
      "Spider-Man",
      "Superman",
      "Thanos",
      "The Flash",
      "The Incredibles",
      "Thor",
      "Venom",
      "Wolverine",
      "Wonder Woman",
      "X-Men",
    ],
  },
  {
    id: "chart-toppers",
    name: "Music",
    description: "Artists and bands from every corner of the charts.",
    symbol: "♫",
    category: "music",
    cards: [
      "ABBA",
      "Adele",
      "Amy Winehouse",
      "Aretha Franklin",
      "Arctic Monkeys",
      "BTS",
      "Beyoncé",
      "Billie Eilish",
      "Bob Marley",
      "Burna Boy",
      "Coldplay",
      "Daft Punk",
      "David Bowie",
      "Dolly Parton",
      "Drake",
      "Ed Sheeran",
      "Elton John",
      "Fleetwood Mac",
      "Freddie Mercury",
      "Jay-Z",
      "Kendrick Lamar",
      "Little Simz",
      "Michael Jackson",
      "Nina Simone",
      "Oasis",
      "Prince",
      "Queen",
      "Rihanna",
      "Stormzy",
      "Taylor Swift",
      "The Beatles",
      "Tina Turner",
    ],
  },
  {
    id: "stage-and-song",
    name: "Musicals & stage",
    description: "Curtain up. Shows, songs, and the people who belt them.",
    symbol: "▲",
    category: "music",
    cards: [
      "A Chorus Line",
      "Aladdin",
      "Annie",
      "Cabaret",
      "Cats",
      "Chicago",
      "Dear Evan Hansen",
      "Everybody's Talking About Jamie",
      "Grease",
      "Hairspray",
      "Hamilton",
      "Jersey Boys",
      "Joseph",
      "Les Misérables",
      "Mamma Mia!",
      "Mary Poppins",
      "Matilda",
      "Moulin Rouge",
      "Oliver!",
      "Phantom of the Opera",
      "Rent",
      "Shakespeare",
      "Six",
      "Sweeney Todd",
      "The Book of Mormon",
      "The Lion King",
      "The Sound of Music",
      "Wicked",
      "West Side Story",
    ],
  },
  {
    id: "on-the-plate",
    name: "Food & drink",
    description: "Dinners, snacks, and the arguments about how to make them.",
    symbol: "◐",
    category: "life",
    cards: [
      "Avocado toast",
      "Bubble tea",
      "Carbonara",
      "Cheese board",
      "Chicken shop",
      "Chocolate fountain",
      "Croissant",
      "Doner kebab",
      "Fish and chips",
      "Full English",
      "Guacamole",
      "Hot sauce",
      "Ice cream van",
      "Jollof rice",
      "Kimchi",
      "Lasagne",
      "Marmite",
      "Nutella",
      "Oat milk",
      "Pad Thai",
      "Pineapple on pizza",
      "Popcorn",
      "Ramen",
      "Roast potatoes",
      "Sourdough",
      "Sushi",
      "Tacos",
      "Toastie",
      "Trifle",
      "Yorkshire tea",
    ],
  },
  {
    id: "creature-feature",
    name: "Animals",
    description: "Household pets, deep-sea oddities, and everything with paws.",
    symbol: "❋",
    category: "world",
    cards: [
      "Alpaca",
      "Axolotl",
      "Badger",
      "Chameleon",
      "Corgi",
      "Dolphin",
      "Elephant",
      "Flamingo",
      "Fox",
      "Giraffe",
      "Golden retriever",
      "Hedgehog",
      "Hippo",
      "Jellyfish",
      "Kangaroo",
      "Koala",
      "Meerkat",
      "Octopus",
      "Orca",
      "Otter",
      "Panda",
      "Penguin",
      "Pigeon",
      "Platypus",
      "Polar bear",
      "Puffin",
      "Red panda",
      "Sloth",
      "Tarantula",
      "Tortoise",
    ],
  },
  {
    id: "far-and-wide",
    name: "Around the world",
    description: "Cities, landmarks, and places worth the flight.",
    symbol: "◍",
    category: "world",
    cards: [
      "Amazon rainforest",
      "Angkor Wat",
      "Bondi Beach",
      "Colosseum",
      "Copenhagen",
      "Eiffel Tower",
      "Golden Gate Bridge",
      "Grand Canyon",
      "Great Barrier Reef",
      "Great Wall of China",
      "Iceland",
      "Istanbul",
      "Kyoto",
      "Lagos",
      "Machu Picchu",
      "Marrakesh",
      "Mount Everest",
      "Mount Fuji",
      "Niagara Falls",
      "Northern Lights",
      "Petra",
      "Pyramids of Giza",
      "Rio de Janeiro",
      "Sahara Desert",
      "Santorini",
      "Statue of Liberty",
      "Stonehenge",
      "Sydney Opera House",
      "Taj Mahal",
      "Times Square",
      "Venice",
    ],
  },
  {
    id: "sporting-chance",
    name: "Sport",
    description: "Games, gear, and the moments people still argue about.",
    symbol: "◎",
    category: "active",
    cards: [
      "Ballet",
      "Bungee jumping",
      "Cricket",
      "Cycling",
      "Darts",
      "Formula 1",
      "Golf",
      "Gymnastics",
      "Ice hockey",
      "Judo",
      "Marathon",
      "Netball",
      "Olympics",
      "Ping pong",
      "Pole vault",
      "Rock climbing",
      "Rounders",
      "Rugby",
      "Serena Williams",
      "Skateboarding",
      "Snooker",
      "Sumo wrestling",
      "Surfing",
      "Swimming",
      "The World Cup",
      "Tour de France",
      "Usain Bolt",
      "VAR",
      "Wimbledon",
      "Yoga",
    ],
  },
  {
    id: "worth-a-read",
    name: "Books & characters",
    description: "Shelf classics and the characters that outgrew them.",
    symbol: "▤",
    category: "screen",
    cards: [
      "Alice in Wonderland",
      "Anne of Green Gables",
      "Bilbo Baggins",
      "Charlotte's Web",
      "Dracula",
      "Frankenstein",
      "Gandalf",
      "Great Expectations",
      "Hermione Granger",
      "Jane Eyre",
      "Katniss Everdeen",
      "Lord of the Rings",
      "Malorie Blackman",
      "Matilda",
      "Moby Dick",
      "Narnia",
      "Nineteen Eighty-Four",
      "Percy Jackson",
      "Peter Pan",
      "Pride and Prejudice",
      "Roald Dahl",
      "Robinson Crusoe",
      "Sherlock Holmes",
      "The Gruffalo",
      "The Hunger Games",
      "The Very Hungry Caterpillar",
      "Toni Morrison",
      "Treasure Island",
      "Winnie the Pooh",
      "Wuthering Heights",
    ],
  },
  {
    id: "throwback",
    name: "Throwback",
    description: "The 90s and 00s, exactly as you left them.",
    symbol: "◑",
    category: "mixed",
    cards: [
      "Blockbuster",
      "Bratz dolls",
      "Burned CDs",
      "Chatrooms",
      "Dial-up internet",
      "Disposable camera",
      "Flip phone",
      "Furby",
      "Game Boy",
      "Gel pens",
      "Heelys",
      "Hit Clips",
      "Instant messenger",
      "iPod",
      "Juicy tracksuit",
      "Limewire",
      "Low-rise jeans",
      "MSN Messenger",
      "MySpace",
      "Nokia 3310",
      "Polly Pocket",
      "Pop-up ads",
      "Ringtones",
      "Skip It",
      "Tamagotchi",
      "The Walkman",
      "Trading cards",
      "VHS tape",
      "Video rental shop",
      "Yo-yo",
    ],
  },
  {
    id: "online",
    name: "Very online",
    description: "Apps, memes, and the strange rituals of the internet.",
    symbol: "◇",
    category: "mixed",
    cards: [
      "Autocorrect fail",
      "Cat video",
      "Doomscrolling",
      "Group chat",
      "Influencer",
      "Instagram",
      "Left on read",
      "Loading spinner",
      "Meme",
      "Notifications off",
      "Out of office",
      "Podcast",
      "Reply all",
      "Screenshot",
      "Screen time report",
      "Slack",
      "Spam email",
      "Spotify Wrapped",
      "Subscribing",
      "TikTok",
      "Two-factor code",
      "Unboxing video",
      "Unread emails",
      "Voice note",
      "VPN",
      "WhatsApp",
      "Wi-Fi password",
      "YouTube",
      "Zoom call",
    ],
  },
  {
    id: "day-job",
    name: "Jobs",
    description: "What people actually do all day, plus a few dream ones.",
    symbol: "▥",
    category: "life",
    cards: [
      "Air traffic controller",
      "Architect",
      "Astronaut",
      "Barista",
      "Bin collector",
      "Bus driver",
      "Chef",
      "Dentist",
      "Electrician",
      "Estate agent",
      "Firefighter",
      "Florist",
      "Hairdresser",
      "Journalist",
      "Judge",
      "Lifeguard",
      "Midwife",
      "Nurse",
      "Paramedic",
      "Pilot",
      "Plumber",
      "Police officer",
      "Postman",
      "Referee",
      "Scientist",
      "Software developer",
      "Teacher",
      "Tattoo artist",
      "Vet",
      "Window cleaner",
    ],
  },
  {
    id: "small-people",
    name: "Family friendly",
    description: "Gentle cards for playing with younger kids.",
    symbol: "○",
    category: "mixed",
    cards: [
      "Balloon",
      "Bicycle",
      "Birthday cake",
      "Bubbles",
      "Butterfly",
      "Castle",
      "Dinosaur",
      "Doctor",
      "Elephant",
      "Fire engine",
      "Football",
      "Ice cream",
      "Kite",
      "Ladybird",
      "Mermaid",
      "Monkey",
      "Moon",
      "Pirate",
      "Playground",
      "Puppy",
      "Rainbow",
      "Robot",
      "Rocket",
      "Sandcastle",
      "Snowman",
      "Superhero",
      "Teddy bear",
      "Train",
      "Umbrella",
      "Wizard",
    ],
  },
  {
    id: "big-questions",
    name: "Science & space",
    description: "The universe, the very small, and the people who explained it.",
    symbol: "✧",
    category: "world",
    cards: [
      "Albert Einstein",
      "Antibiotics",
      "Big Bang",
      "Black hole",
      "Charles Darwin",
      "DNA",
      "Earthquake",
      "Eclipse",
      "Evolution",
      "Gravity",
      "Greenhouse effect",
      "Hubble Telescope",
      "International Space Station",
      "Isaac Newton",
      "Jupiter",
      "Lightning",
      "Marie Curie",
      "Mars rover",
      "Microscope",
      "Milky Way",
      "Moon landing",
      "Periodic table",
      "Photosynthesis",
      "Rosalind Franklin",
      "Saturn's rings",
      "Solar panel",
      "Stephen Hawking",
      "Telescope",
      "Vaccine",
      "Volcano",
    ],
  },
] satisfies readonly GameDeck[];

export function shuffledCards(cards: readonly string[]) {
  const next = [...cards];
  for (let index = next.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [next[index], next[swapIndex]] = [next[swapIndex], next[index]];
  }
  return next;
}
