/**
 * The imposter word bank, browser-safe.
 *
 * Not a secret: knowing that "beach / desert" is one of 259 possible pairs tells you nothing about
 * which one was dealt, and the room game's secrecy lives in the snapshot rather than in this list
 * being hidden. Keeping it here means the one-phone mode can deal a game with no server at all.
 */
export interface LiarsWordPair {
  /** What the crew are given. */
  word: string;
  /** What the understudy is given — close enough to survive a round, wrong enough to surface. */
  decoy: string;
}

/**
 * The pairing is the whole mechanic. Too far apart and the understudy is obvious on their first
 * clue; too close and the role is indistinguishable from a crew member and nobody can win. Each of
 * these shares a first association and diverges on the second or third.
 */
export const LIARS_WORD_PAIRS: LiarsWordPair[] = [
  { word: "beach", decoy: "desert" },
  { word: "library", decoy: "museum" },
  { word: "hospital", decoy: "school" },
  { word: "wedding", decoy: "funeral" },
  { word: "airport", decoy: "train station" },
  { word: "cinema", decoy: "theatre" },
  { word: "guitar", decoy: "piano" },
  { word: "coffee", decoy: "tea" },
  { word: "winter", decoy: "autumn" },
  { word: "volcano", decoy: "mountain" },
  { word: "pirate", decoy: "viking" },
  { word: "dentist", decoy: "barber" },
  { word: "prison", decoy: "boarding school" },
  { word: "circus", decoy: "carnival" },
  { word: "submarine", decoy: "spaceship" },
  { word: "vampire", decoy: "ghost" },
  { word: "marathon", decoy: "triathlon" },
  { word: "casino", decoy: "arcade" },
  { word: "farm", decoy: "zoo" },
  { word: "bakery", decoy: "butcher" },
  { word: "lighthouse", decoy: "windmill" },
  { word: "aquarium", decoy: "greenhouse" },
  { word: "snow", decoy: "sand" },
  { word: "detective", decoy: "journalist" },
  { word: "campfire", decoy: "fireplace" },
  { word: "helicopter", decoy: "hot air balloon" },
  { word: "supermarket", decoy: "market stall" },
  { word: "swimming pool", decoy: "lake" },
  { word: "birthday", decoy: "anniversary" },
  { word: "chess", decoy: "poker" },
  { word: "umbrella", decoy: "raincoat" },
  { word: "castle", decoy: "cathedral" },
  { word: "orchestra", decoy: "choir" },
  { word: "desert island", decoy: "shipwreck" },
  { word: "laundry", decoy: "dishwashing" },
  { word: "haircut", decoy: "tattoo" },
  { word: "earthquake", decoy: "thunderstorm" },
  { word: "honeymoon", decoy: "road trip" },
  { word: "bicycle", decoy: "motorbike" },
  { word: "greenhouse", decoy: "allotment" },
  { word: "opera", decoy: "ballet" },
  { word: "safari", decoy: "hiking" },
  { word: "post office", decoy: "bank" },
  { word: "graveyard", decoy: "battlefield" },
  { word: "museum", decoy: "art gallery" },
  { word: "nightclub", decoy: "pub" },
  { word: "ski resort", decoy: "spa hotel" },
  { word: "courtroom", decoy: "parliament" },
  { word: "kitchen", decoy: "workshop" },
  { word: "attic", decoy: "basement" },
  { word: "sunrise", decoy: "sunset" },
  { word: "cactus", decoy: "pine tree" },
  { word: "magician", decoy: "clown" },
  { word: "astronaut", decoy: "deep sea diver" },
  { word: "wedding cake", decoy: "birthday cake" },
  { word: "petrol station", decoy: "car wash" },
  { word: "photograph", decoy: "painting" },
  { word: "thunder", decoy: "fireworks" },
  { word: "honey", decoy: "syrup" },
  { word: "mirror", decoy: "window" },
  { word: "elevator", decoy: "escalator" },
  { word: "waterfall", decoy: "fountain" },
  { word: "bookshop", decoy: "record shop" },
  { word: "chef", decoy: "waiter" },
  { word: "fog", decoy: "smoke" },
  { word: "penguin", decoy: "seal" },
  { word: "hotel lobby", decoy: "waiting room" },
  { word: "hurricane", decoy: "blizzard" },
  { word: "violin", decoy: "cello" },
  { word: "tent", decoy: "caravan" },
  { word: "island", decoy: "peninsula" },
  { word: "ambulance", decoy: "fire engine" },
  { word: "chessboard", decoy: "crossword" },
  { word: "moustache", decoy: "beard" },
  { word: "harvest", decoy: "planting" },
  { word: "auction", decoy: "raffle" },
  { word: "cathedral", decoy: "mosque" },
  { word: "ferry", decoy: "cruise ship" },
  { word: "puppy", decoy: "kitten" },
  { word: "avalanche", decoy: "landslide" },
  { word: "tailor", decoy: "cobbler" },
  { word: "telescope", decoy: "microscope" },
  { word: "carnival mask", decoy: "gas mask" },
  { word: "bonfire", decoy: "barbecue" },
  { word: "labyrinth", decoy: "obstacle course" },
  { word: "monastery", decoy: "boarding house" },
  { word: "quicksand", decoy: "swamp" },
  { word: "typewriter", decoy: "sewing machine" },
  { word: "eclipse", decoy: "aurora" },
  { word: "orchard", decoy: "vineyard" },
  { word: "stadium", decoy: "amphitheatre" },
  { word: "cellar", decoy: "pantry" },
  { word: "seagull", decoy: "pigeon" },
  { word: "compass", decoy: "map" },
  { word: "hammock", decoy: "deckchair" },
  { word: "shipyard", decoy: "scrapyard" },
  { word: "midnight", decoy: "dawn" },
  { word: "acrobat", decoy: "gymnast" },
  { word: "greengrocer", decoy: "fishmonger" },
  { word: "sandcastle", decoy: "snowman" },
  { word: "rehearsal", decoy: "audition" },
  { word: "moth", decoy: "butterfly" },
  { word: "canyon", decoy: "fjord" },
  { word: "postcard", decoy: "letter" },
  { word: "sauna", decoy: "greenhouse" },
  { word: "trampoline", decoy: "diving board" },
  { word: "pharmacy", decoy: "corner shop" },
  { word: "lullaby", decoy: "anthem" },
  { word: "windmill", decoy: "water wheel" },
  { word: "custard", decoy: "gravy" },
  { word: "hedge maze", decoy: "hall of mirrors" },
  { word: "roadworks", decoy: "building site" },
  { word: "harbour", decoy: "marina" },
  { word: "referee", decoy: "lifeguard" },
  { word: "scarecrow", decoy: "statue" },
  { word: "chandelier", decoy: "campfire" },
  { word: "swamp", decoy: "marsh" },
  { word: "attic ladder", decoy: "fire escape" },
  { word: "monsoon", decoy: "drought" },
  { word: "puppet", decoy: "doll" },
  { word: "conveyor belt", decoy: "assembly line" },
  { word: "glacier", decoy: "iceberg" },
  { word: "pilgrimage", decoy: "expedition" },
  { word: "junk drawer", decoy: "toolbox" },
  { word: "lantern", decoy: "torch" },
  { word: "quarry", decoy: "mine" },
  { word: "revolving door", decoy: "turnstile" },
  { word: "tea room", decoy: "canteen" },
  { word: "vending machine", decoy: "cash machine" },
  { word: "whirlpool", decoy: "riptide" },
  { word: "yacht", decoy: "rowing boat" },
  { word: "zeppelin", decoy: "glider" },
  { word: "allotment", decoy: "back garden" },
  { word: "blacksmith", decoy: "carpenter" },
  { word: "chimney", decoy: "drainpipe" },
  { word: "duvet", decoy: "sleeping bag" },
  { word: "escalator", decoy: "travelator" },
  { word: "fishing rod", decoy: "butterfly net" },
  { word: "grandfather clock", decoy: "cuckoo clock" },
  { word: "haystack", decoy: "compost heap" },
  { word: "igloo", decoy: "log cabin" },
  { word: "jigsaw", decoy: "dominoes" },
  { word: "kaleidoscope", decoy: "prism" },
  { word: "lifeboat", decoy: "raft" },
  { word: "megaphone", decoy: "whistle" },
  { word: "nursery", decoy: "playground" },
  { word: "observatory", decoy: "control tower" },
  { word: "parachute", decoy: "kite" },
  { word: "quilt", decoy: "tapestry" },
  { word: "radiator", decoy: "kettle" },
  { word: "seesaw", decoy: "swing" },
  { word: "treehouse", decoy: "shed" },
  { word: "umbrella stand", decoy: "coat rack" },
  { word: "vineyard", decoy: "brewery" },
  { word: "wheelbarrow", decoy: "trolley" },
  { word: "x-ray", decoy: "photocopy" },
  { word: "yoga class", decoy: "dance class" },
  { word: "zoo keeper", decoy: "vet" },
  { word: "barbershop", decoy: "nail salon" },
  { word: "launderette", decoy: "internet cafe" },
  { word: "ice rink", decoy: "roller disco" },
  { word: "planetarium", decoy: "cinema" },
  { word: "morgue", decoy: "operating theatre" },
  { word: "call centre", decoy: "newsroom" },
  { word: "boot sale", decoy: "jumble sale" },
  { word: "allotment shed", decoy: "beach hut" },
  { word: "rooftop", decoy: "balcony" },
  { word: "bus stop", decoy: "taxi rank" },
  { word: "waiting list", decoy: "queue" },
  { word: "wedding speech", decoy: "eulogy" },
  { word: "first date", decoy: "job interview" },
  { word: "school play", decoy: "talent show" },
  { word: "sports day", decoy: "field trip" },
  { word: "detention", decoy: "assembly" },
  { word: "night shift", decoy: "red eye flight" },
  { word: "power cut", decoy: "water outage" },
  { word: "house move", decoy: "spring clean" },
  { word: "flat pack", decoy: "jigsaw puzzle" },
  { word: "smoke alarm", decoy: "car alarm" },
  { word: "dentist chair", decoy: "barber chair" },
  { word: "waiting room", decoy: "departure lounge" },
  { word: "lost property", decoy: "pawn shop" },
  { word: "car boot", decoy: "attic" },
  { word: "recycling", decoy: "composting" },
  { word: "roadside picnic", decoy: "tailgate" },
  { word: "camping stove", decoy: "kettle" },
  { word: "sleeping bag", decoy: "hammock" },
  { word: "head torch", decoy: "candle" },
  { word: "map reading", decoy: "stargazing" },
  { word: "low tide", decoy: "drought" },
  { word: "rock pool", decoy: "puddle" },
  { word: "shingle beach", decoy: "gravel drive" },
  { word: "pier", decoy: "jetty" },
  { word: "arcade machine", decoy: "jukebox" },
  { word: "photo booth", decoy: "confessional" },
  { word: "revolving stage", decoy: "carousel" },
  { word: "green room", decoy: "dressing room" },
  { word: "encore", decoy: "curtain call" },
  { word: "stage fright", decoy: "writer's block" },
  { word: "understudy", decoy: "stand-in" },
  { word: "conductor", decoy: "choreographer" },
  { word: "metronome", decoy: "pendulum" },
  { word: "record player", decoy: "music box" },
  { word: "mixtape", decoy: "playlist" },
  { word: "busker", decoy: "street artist" },
  { word: "brass band", decoy: "marching band" },
  { word: "karaoke", decoy: "open mic" },
  { word: "silent disco", decoy: "library" },
  { word: "last orders", decoy: "closing time" },
  { word: "corner shop", decoy: "petrol station" },
  { word: "market day", decoy: "car boot sale" },
  { word: "fishmonger", decoy: "deli counter" },
  { word: "sourdough", decoy: "pizza dough" },
  { word: "pickling", decoy: "smoking" },
  { word: "leftovers", decoy: "packed lunch" },
  { word: "sunday roast", decoy: "christmas dinner" },
  { word: "picnic blanket", decoy: "beach towel" },
  { word: "thermos", decoy: "hip flask" },
  { word: "birdwatching", decoy: "fishing" },
  { word: "beehive", decoy: "anthill" },
  { word: "spiderweb", decoy: "fishing net" },
  { word: "hibernation", decoy: "migration" },
  { word: "molehill", decoy: "sand dune" },
  { word: "sheepdog", decoy: "guide dog" },
  { word: "stable", decoy: "kennel" },
  { word: "veterinary", decoy: "paediatric" },
  { word: "microscope slide", decoy: "photo negative" },
  { word: "petri dish", decoy: "ashtray" },
  { word: "laboratory", decoy: "pharmacy" },
  { word: "space station", decoy: "oil rig" },
  { word: "control room", decoy: "cockpit" },
  { word: "black box", decoy: "time capsule" },
  { word: "lighthouse keeper", decoy: "night watchman" },
  { word: "customs", decoy: "security check" },
  { word: "passport", decoy: "membership card" },
  { word: "layover", decoy: "detour" },
  { word: "sleeper train", decoy: "night bus" },
  { word: "cable car", decoy: "chairlift" },
  { word: "roundabout", decoy: "crossroads" },
  { word: "level crossing", decoy: "drawbridge" },
  { word: "toll booth", decoy: "ticket barrier" },
  { word: "hard shoulder", decoy: "lay-by" },
  { word: "speed camera", decoy: "cctv" },
  { word: "parking ticket", decoy: "library fine" },
  { word: "jury duty", decoy: "census" },
  { word: "polling station", decoy: "job centre" },
  { word: "town hall", decoy: "village green" },
  { word: "war memorial", decoy: "bandstand" },
  { word: "bell tower", decoy: "clock tower" },
  { word: "crypt", decoy: "wine cellar" },
  { word: "stained glass", decoy: "mosaic" },
  { word: "pilgrim", decoy: "backpacker" },
  { word: "confession", decoy: "interrogation" },
  { word: "alibi", decoy: "excuse" },
  { word: "fingerprint", decoy: "signature" },
  { word: "witness box", decoy: "pulpit" },
  { word: "verdict", decoy: "diagnosis" },
  { word: "parole", decoy: "graduation" },
  { word: "curfew", decoy: "bedtime" },
];
