const DESCRIPTIONS = [
  "sneaky",
  "cosmic",
  "sleepy",
  "disco",
  "wonky",
  "tiny",
  "fancy",
  "cheeky",
  "wobbly",
  "crispy",
  "mellow",
  "jazzy",
  "lucky",
  "soggy",
  "dizzy",
  "fuzzy",
  "bouncy",
  "breezy",
  "sassy",
  "zesty",
  "fizzy",
  "royal",
  "shifty",
  "wiggly",
  "speedy",
  "chill",
  "dapper",
  "sparkly",
  "jolly",
  "silly",
  "mighty",
  "noisy",
] as const;
const CREATURES = [
  "biscuit",
  "badger",
  "goose",
  "noodle",
  "pigeon",
  "turnip",
  "muffin",
  "llama",
  "pickle",
  "otter",
  "waffle",
  "panda",
  "prawn",
  "penguin",
  "potato",
  "ferret",
  "mango",
  "koala",
  "crumpet",
  "raccoon",
  "parsnip",
  "walrus",
  "donut",
  "duck",
  "bagel",
  "gecko",
  "dumpling",
  "sloth",
  "taco",
  "squirrel",
  "lemon",
  "moose",
  "radish",
  "puffin",
  "pretzel",
  "hedgehog",
  "pepper",
  "shrimp",
  "falafel",
  "frog",
  "churro",
  "hamster",
  "peach",
  "lobster",
  "pancake",
  "parrot",
  "pea",
  "seal",
  "quokka",
  "sardine",
  "apricot",
  "meerkat",
  "coconut",
  "yak",
  "olive",
  "alpaca",
  "sushi",
  "beaver",
  "kiwi",
  "flamingo",
  "custard",
  "wombat",
  "marshmallow",
  "crab",
] as const;

/** An editable display name, never an identity or credential. The seed keeps it stable per visit. */
export function guestNameFromSeed(seed: string) {
  let hash = 2166136261;
  for (const letter of seed) hash = Math.imul(hash ^ letter.charCodeAt(0), 16777619);
  const value = hash >>> 0;
  return `${DESCRIPTIONS[value % DESCRIPTIONS.length]} ${CREATURES[Math.floor(value / DESCRIPTIONS.length) % CREATURES.length]}`;
}
