import { randomInt } from "node:crypto";

import { HOT_AND_COLD_DAILY_SCHEDULE } from "./hot-and-cold-daily-schedule.server";

/** Curated targets. General guesses remain open; targets need reliable semantic neighbourhoods. */
export const HOT_AND_COLD_TARGETS = [
  "airport",
  "anchor",
  "apple",
  "avalanche",
  "bakery",
  "balloon",
  "beach",
  "bicycle",
  "blanket",
  "bridge",
  "butterfly",
  "camera",
  "candle",
  "castle",
  "cave",
  "cheese",
  "chimney",
  "circus",
  "clock",
  "cloud",
  "coffee",
  "comet",
  "compass",
  "concert",
  "crown",
  "desert",
  "diamond",
  "dinosaur",
  "doctor",
  "dragon",
  "dream",
  "earthquake",
  "engine",
  "feather",
  "festival",
  "fireplace",
  "forest",
  "fountain",
  "garden",
  "ghost",
  "glacier",
  "guitar",
  "harbour",
  "helmet",
  "honey",
  "hospital",
  "island",
  "jungle",
  "kettle",
  "kingdom",
  "ladder",
  "lantern",
  "library",
  "lighthouse",
  "lightning",
  "market",
  "mirror",
  "moon",
  "mountain",
  "museum",
  "music",
  "ocean",
  "orchard",
  "painting",
  "passport",
  "piano",
  "picnic",
  "pirate",
  "planet",
  "prison",
  "rainbow",
  "river",
  "robot",
  "rocket",
  "sandwich",
  "school",
  "shadow",
  "ship",
  "snowman",
  "stadium",
  "storm",
  "submarine",
  "sunrise",
  "telescope",
  "theatre",
  "thunder",
  "tiger",
  "tower",
  "train",
  "treasure",
  "tunnel",
  "umbrella",
  "village",
  "volcano",
  "waterfall",
  "wedding",
  "whistle",
  "window",
  "winter",
  "wizard",
  "accordion",
  "adventure",
  "ambulance",
  "angel",
  "ant",
  "apartment",
  "archer",
  "armour",
  "artist",
  "astronaut",
  "autumn",
  "backpack",
  "badger",
  "banana",
  "bank",
  "barber",
  "barn",
  "basket",
  "bathroom",
  "battery",
  "battle",
  "bear",
  "bell",
  "bench",
  "bird",
  "birthday",
  "boat",
  "book",
  "bottle",
  "bowl",
  "box",
  "bread",
  "breakfast",
  "breeze",
  "brick",
  "brother",
  "brush",
  "bubble",
  "bucket",
  "bus",
  "cabinet",
  "cactus",
  "calendar",
  "campfire",
  "canal",
  "captain",
  "carpet",
  "carrot",
  "cartoon",
  "cat",
  "cathedral",
  "chair",
  "chocolate",
  "cinema",
  "clown",
  "coat",
  "coconut",
  "coin",
  "college",
  "computer",
  "cooking",
  "cottage",
  "cowboy",
  "crab",
  "crystal",
  "cupboard",
  "curtain",
  "dance",
  "dentist",
  "diary",
  "dinner",
  "dog",
  "dolphin",
  "door",
  "drum",
  "duck",
  "eagle",
  "elephant",
  "elevator",
  "emerald",
  "envelope",
  "factory",
  "fairy",
  "family",
  "farmer",
  "ferry",
  "finger",
  "fishing",
  "flower",
  "flute",
  "football",
  "fork",
  "friendship",
  "frog",
  "garage",
  "garlic",
  "giant",
  "giraffe",
  "glove",
  "gold",
  "goose",
  "grape",
  "grass",
  "hammer",
  "hamster",
  "hat",
  "hedgehog",
  "helicopter",
  "horse",
  "hotel",
  "iceberg",
  "jacket",
  "jellyfish",
  "jewel",
  "journey",
  "kangaroo",
  "key",
  "kitchen",
  "kite",
  "knife",
  "lake",
  "lemon",
  "lion",
  "lobster",
  "magnet",
  "mermaid",
  "monkey",
  "motorcycle",
  "mushroom",
  "necklace",
  "newspaper",
  "nightmare",
  "octopus",
  "onion",
  "orange",
  "owl",
  "panda",
  "paper",
  "parade",
  "parrot",
  "pencil",
  "penguin",
  "pepper",
  "photograph",
  "pigeon",
  "pillow",
  "pizza",
  "playground",
  "pocket",
  "potato",
  "queen",
  "rabbit",
  "radio",
  "rain",
  "restaurant",
  "ring",
  "road",
  "robin",
  "ruby",
  "sailor",
  "scarf",
  "shark",
  "shoe",
  "sister",
  "skeleton",
  "snake",
  "soap",
  "spider",
  "spoon",
  "spring",
  "star",
  "summer",
  "sun",
  "swan",
  "sword",
  "table",
  "taxi",
  "telephone",
  "tent",
  "toothbrush",
  "tornado",
  "tractor",
  "traffic",
  "trumpet",
  "turtle",
  "unicorn",
  "violin",
  "wallet",
  "whale",
  "windmill",
  "wolf",
  "zebra",
] as const;

export type HotAndColdTarget = (typeof HOT_AND_COLD_TARGETS)[number];

/**
 * The ordinary sense intended by each otherwise ambiguous target. Targets not
 * listed here use their first noun sense. IDs pin Open English WordNet 2025.
 */
export const HOT_AND_COLD_TARGET_SENSES: Partial<Record<HotAndColdTarget, string>> = {
  armour: "oewn-02742673-n",
  banana: "oewn-07769568-n",
  bank: "oewn-08437235-n",
  battery: "oewn-02813606-n",
  brush: "oewn-02911542-n",
  canal: "oewn-02950684-n",
  captain: "oewn-10318579-n",
  castle: "oewn-02983900-n",
  chocolate: "oewn-07617570-n",
  cinema: "oewn-03036237-n",
  clown: "oewn-09950334-n",
  cloud: "oewn-09270316-n",
  coconut: "oewn-07788911-n",
  college: "oewn-08295245-n",
  cowboy: "oewn-86290056-n",
  crown: "oewn-03143320-n",
  dolphin: "oewn-02071627-n",
  flower: "oewn-11689786-n",
  garlic: "oewn-07834253-n",
  ghost: "oewn-09569105-n",
  glove: "oewn-03446036-n",
  gold: "oewn-14662977-n",
  hammer: "oewn-03486255-n",
  hedgehog: "oewn-01896466-n",
  jellyfish: "oewn-01913388-n",
  jungle: "oewn-08456014-n",
  kingdom: "oewn-08575692-n",
  kite: "oewn-03626682-n",
  lobster: "oewn-01985291-n",
  moon: "oewn-09381123-n",
  nightmare: "oewn-05777059-n",
  octopus: "oewn-01972805-n",
  passport: "oewn-06512928-n",
  pepper: "oewn-07736187-n",
  pirate: "oewn-10455134-n",
  queen: "oewn-10518940-n",
  radio: "oewn-04050813-n",
  ring: "oewn-04099721-n",
  scarf: "oewn-04150962-n",
  skeleton: "oewn-05593033-n",
  sun: "oewn-09473603-n",
  table: "oewn-04386330-n",
  tiger: "oewn-02132256-n",
  turtle: "oewn-01665425-n",
  whale: "oewn-02065397-n",
  whistle: "oewn-04586953-n",
  wizard: "oewn-10645222-n",
};

const DAILY_EPOCH = Date.UTC(2026, 7, 25);
const UK_DAY = new Intl.DateTimeFormat("en-GB", {
  timeZone: "Europe/London",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
});

function ukDay(date: Date): number {
  const parts = Object.fromEntries(
    UK_DAY.formatToParts(date)
      .filter(({ type }) => type !== "literal")
      .map(({ type, value }) => [type, Number(value)]),
  );
  return Date.UTC(parts.year, parts.month - 1, parts.day);
}

export function hotAndColdPuzzleNumber(date = new Date()) {
  return Math.max(1, Math.floor((ukDay(date) - DAILY_EPOCH) / 86_400_000) + 1);
}

export function hotAndColdTargetForPuzzle(puzzle: number) {
  const offset = Math.max(0, Math.floor(puzzle) - 1);
  return HOT_AND_COLD_DAILY_SCHEDULE[offset % HOT_AND_COLD_DAILY_SCHEDULE.length];
}

export function dailyHotAndColdTarget(date = new Date()) {
  return hotAndColdTargetForPuzzle(hotAndColdPuzzleNumber(date));
}

export function hotAndColdPuzzleDate(puzzle: number) {
  return new Date(DAILY_EPOCH + (Math.max(1, Math.floor(puzzle)) - 1) * 86_400_000)
    .toISOString()
    .slice(0, 10);
}

export function previousHotAndColdPuzzles(date = new Date()) {
  const current = hotAndColdPuzzleNumber(date);
  return Array.from({ length: current - 1 }, (_unused, index) => {
    const puzzle = current - index - 1;
    return {
      puzzle,
      date: hotAndColdPuzzleDate(puzzle),
    };
  });
}

export function randomHotAndColdTargets(
  total: number,
  excluded: readonly string[] = [],
  pick: (upperBound: number) => number = randomInt,
) {
  const fresh = HOT_AND_COLD_TARGETS.filter((word) => !excluded.includes(word));
  const pool = [...(fresh.length >= total ? fresh : HOT_AND_COLD_TARGETS)];
  const selected: string[] = [];
  while (pool.length > 0 && selected.length < total) {
    selected.push(...pool.splice(pick(pool.length), 1));
  }
  return selected;
}
