/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ThingsRouteImport } from './routes/things'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartyRouteImport } from './routes/party'
import { Route as IcebreakerRouteImport } from './routes/icebreaker'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GuestlistRouteImport } from './routes/guestlist'
import { Route as FontTestRouteImport } from './routes/font-test'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as BestDressedRouteImport } from './routes/best-dressed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordsIndexRouteImport } from './routes/words/index'
import { Route as PicsIndexRouteImport } from './routes/pics/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WordsSlugRouteImport } from './routes/words/$slug'
import { Route as VaultSlugRouteImport } from './routes/vault/$slug'
import { Route as ThingsIcebreakerRouteImport } from './routes/things.icebreaker'
import { Route as ThingsHeadsUpRouteImport } from './routes/things.heads-up'
import { Route as TIdRouteImport } from './routes/t/$id'
import { Route as AdminEditorRouteImport } from './routes/admin/editor'
import { Route as ApiWordsRouteRouteImport } from './routes/api/words/route'
import { Route as ApiHealthRouteRouteImport } from './routes/api/health/route'
import { Route as ApiGuestsRouteRouteImport } from './routes/api/guests/route'
import { Route as ApiDebugRouteRouteImport } from './routes/api/debug/route'
import { Route as ApiBestDressedRouteRouteImport } from './routes/api/best-dressed/route'
import { Route as PicsAlbumIndexRouteImport } from './routes/pics/$album/index'
import { Route as PicsAlbumPhotoRouteImport } from './routes/pics/$album/$photo'
import { Route as ApiWordsSlugRouteRouteImport } from './routes/api/words/$slug/route'
import { Route as ApiUploadVerifyPinRouteRouteImport } from './routes/api/upload/verify-pin/route'
import { Route as ApiTransfersIdRouteRouteImport } from './routes/api/transfers/$id/route'
import { Route as ApiGuestsVerifyStaffPinRouteRouteImport } from './routes/api/guests/verify-staff-pin/route'
import { Route as ApiDownloadPresignRouteRouteImport } from './routes/api/download/presign/route'
import { Route as ApiCronProcessTransferMediaRouteRouteImport } from './routes/api/cron/process-transfer-media/route'
import { Route as ApiCronCleanupWordSharesRouteRouteImport } from './routes/api/cron/cleanup-word-shares/route'
import { Route as ApiCronCleanupWordMediaOrphansRouteRouteImport } from './routes/api/cron/cleanup-word-media-orphans/route'
import { Route as ApiCronCleanupTransfersRouteRouteImport } from './routes/api/cron/cleanup-transfers/route'
import { Route as ApiAdminWordSharesRouteRouteImport } from './routes/api/admin/word-shares/route'
import { Route as ApiAdminWordMediaRouteRouteImport } from './routes/api/admin/word-media/route'
import { Route as ApiAdminVerifyRouteRouteImport } from './routes/api/admin/verify/route'
import { Route as ApiAdminTransfersRouteRouteImport } from './routes/api/admin/transfers/route'
import { Route as ApiAdminStepUpRouteRouteImport } from './routes/api/admin/step-up/route'
import { Route as ApiAdminContentSummaryRouteRouteImport } from './routes/api/admin/content-summary/route'
import { Route as ApiAdminContentAuditRouteRouteImport } from './routes/api/admin/content-audit/route'
import { Route as ApiAdminAlbumsRouteRouteImport } from './routes/api/admin/albums/route'
import { Route as ApiWordsShareVerifyRouteRouteImport } from './routes/api/words/share/verify/route'
import { Route as ApiWordsSlugSharesRouteRouteImport } from './routes/api/words/$slug/shares/route'
import { Route as ApiUploadWordsTargetsRouteRouteImport } from './routes/api/upload/words/targets/route'
import { Route as ApiUploadWordsPresignRouteRouteImport } from './routes/api/upload/words/presign/route'
import { Route as ApiUploadWordsFinalizeRouteRouteImport } from './routes/api/upload/words/finalize/route'
import { Route as ApiUploadTransferPresignRouteRouteImport } from './routes/api/upload/transfer/presign/route'
import { Route as ApiUploadTransferFinalizeRouteRouteImport } from './routes/api/upload/transfer/finalize/route'
import { Route as ApiBestDressedVotingOpenRouteRouteImport } from './routes/api/best-dressed/voting/open/route'
import { Route as ApiBestDressedCodesRevokeAllRouteRouteImport } from './routes/api/best-dressed/codes/revoke-all/route'
import { Route as ApiBestDressedCodesMintBatchRouteRouteImport } from './routes/api/best-dressed/codes/mint-batch/route'
import { Route as ApiBestDressedCodesMintRouteRouteImport } from './routes/api/best-dressed/codes/mint/route'
import { Route as ApiAdminWordSharesCleanupRouteRouteImport } from './routes/api/admin/word-shares/cleanup/route'
import { Route as ApiAdminWordMediaOrphansRouteRouteImport } from './routes/api/admin/word-media/orphans/route'
import { Route as ApiAdminTransfersProcessMediaRouteRouteImport } from './routes/api/admin/transfers/process-media/route'
import { Route as ApiAdminTransfersNukeRouteRouteImport } from './routes/api/admin/transfers/nuke/route'
import { Route as ApiAdminTransfersCleanupRouteRouteImport } from './routes/api/admin/transfers/cleanup/route'
import { Route as ApiAdminTransfersIdRouteRouteImport } from './routes/api/admin/transfers/$id/route'
import { Route as ApiAdminTokensSessionsRouteRouteImport } from './routes/api/admin/tokens/sessions/route'
import { Route as ApiAdminTokensRevokeRouteRouteImport } from './routes/api/admin/tokens/revoke/route'
import { Route as ApiAdminGuestsRemoveRouteRouteImport } from './routes/api/admin/guests/remove/route'
import { Route as ApiAdminGuestsImportRouteRouteImport } from './routes/api/admin/guests/import/route'
import { Route as ApiAdminGuestsBootstrapRouteRouteImport } from './routes/api/admin/guests/bootstrap/route'
import { Route as ApiAdminGuestsAddRouteRouteImport } from './routes/api/admin/guests/add/route'
import { Route as ApiAdminAlbumsSlugRouteRouteImport } from './routes/api/admin/albums/$slug/route'
import { Route as ApiWordsSlugSharesIdRouteRouteImport } from './routes/api/words/$slug/shares/$id/route'
import { Route as ApiUploadTransferAppendPresignRouteRouteImport } from './routes/api/upload/transfer/append/presign/route'
import { Route as ApiUploadTransferAppendFinalizeRouteRouteImport } from './routes/api/upload/transfer/append/finalize/route'
import { Route as ApiTransfersIdFilesFileIdRouteRouteImport } from './routes/api/transfers/$id/files/$fileId/route'
import { Route as ApiAdminTokensSessionsJtiRouteRouteImport } from './routes/api/admin/tokens/sessions/$jti/route'
import { Route as ApiAdminAlbumsSlugCoverRouteRouteImport } from './routes/api/admin/albums/$slug/cover/route'
import { Route as ApiTransfersIdMediaFileIdVariantRouteRouteImport } from './routes/api/transfers/$id/media/$fileId/$variant/route'
import { Route as ApiAdminAlbumsSlugPhotosPhotoIdRouteRouteImport } from './routes/api/admin/albums/$slug/photos/$photoId/route'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ThingsRoute = ThingsRouteImport.update({
  id: '/things',
  path: '/things',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const IcebreakerRoute = IcebreakerRouteImport.update({
  id: '/icebreaker',
  path: '/icebreaker',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestlistRoute = GuestlistRouteImport.update({
  id: '/guestlist',
  path: '/guestlist',
  getParentRoute: () => rootRouteImport,
} as any)
const FontTestRoute = FontTestRouteImport.update({
  id: '/font-test',
  path: '/font-test',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const BestDressedRoute = BestDressedRouteImport.update({
  id: '/best-dressed',
  path: '/best-dressed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsIndexRoute = WordsIndexRouteImport.update({
  id: '/words/',
  path: '/words/',
  getParentRoute: () => rootRouteImport,
} as any)
const PicsIndexRoute = PicsIndexRouteImport.update({
  id: '/pics/',
  path: '/pics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsSlugRoute = WordsSlugRouteImport.update({
  id: '/words/$slug',
  path: '/words/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultSlugRoute = VaultSlugRouteImport.update({
  id: '/vault/$slug',
  path: '/vault/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThingsIcebreakerRoute = ThingsIcebreakerRouteImport.update({
  id: '/icebreaker',
  path: '/icebreaker',
  getParentRoute: () => ThingsRoute,
} as any)
const ThingsHeadsUpRoute = ThingsHeadsUpRouteImport.update({
  id: '/heads-up',
  path: '/heads-up',
  getParentRoute: () => ThingsRoute,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorRoute = AdminEditorRouteImport.update({
  id: '/admin/editor',
  path: '/admin/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordsRouteRoute = ApiWordsRouteRouteImport.update({
  id: '/api/words',
  path: '/api/words',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRouteRoute = ApiHealthRouteRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestsRouteRoute = ApiGuestsRouteRouteImport.update({
  id: '/api/guests',
  path: '/api/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugRouteRoute = ApiDebugRouteRouteImport.update({
  id: '/api/debug',
  path: '/api/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBestDressedRouteRoute = ApiBestDressedRouteRouteImport.update({
  id: '/api/best-dressed',
  path: '/api/best-dressed',
  getParentRoute: () => rootRouteImport,
} as any)
const PicsAlbumIndexRoute = PicsAlbumIndexRouteImport.update({
  id: '/pics/$album/',
  path: '/pics/$album/',
  getParentRoute: () => rootRouteImport,
} as any)
const PicsAlbumPhotoRoute = PicsAlbumPhotoRouteImport.update({
  id: '/pics/$album/$photo',
  path: '/pics/$album/$photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordsSlugRouteRoute = ApiWordsSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiWordsRouteRoute,
} as any)
const ApiUploadVerifyPinRouteRoute = ApiUploadVerifyPinRouteRouteImport.update({
  id: '/api/upload/verify-pin',
  path: '/api/upload/verify-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransfersIdRouteRoute = ApiTransfersIdRouteRouteImport.update({
  id: '/api/transfers/$id',
  path: '/api/transfers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuestsVerifyStaffPinRouteRoute =
  ApiGuestsVerifyStaffPinRouteRouteImport.update({
    id: '/verify-staff-pin',
    path: '/verify-staff-pin',
    getParentRoute: () => ApiGuestsRouteRoute,
  } as any)
const ApiDownloadPresignRouteRoute = ApiDownloadPresignRouteRouteImport.update({
  id: '/api/download/presign',
  path: '/api/download/presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronProcessTransferMediaRouteRoute =
  ApiCronProcessTransferMediaRouteRouteImport.update({
    id: '/api/cron/process-transfer-media',
    path: '/api/cron/process-transfer-media',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronCleanupWordSharesRouteRoute =
  ApiCronCleanupWordSharesRouteRouteImport.update({
    id: '/api/cron/cleanup-word-shares',
    path: '/api/cron/cleanup-word-shares',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronCleanupWordMediaOrphansRouteRoute =
  ApiCronCleanupWordMediaOrphansRouteRouteImport.update({
    id: '/api/cron/cleanup-word-media-orphans',
    path: '/api/cron/cleanup-word-media-orphans',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronCleanupTransfersRouteRoute =
  ApiCronCleanupTransfersRouteRouteImport.update({
    id: '/api/cron/cleanup-transfers',
    path: '/api/cron/cleanup-transfers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminWordSharesRouteRoute = ApiAdminWordSharesRouteRouteImport.update({
  id: '/api/admin/word-shares',
  path: '/api/admin/word-shares',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWordMediaRouteRoute = ApiAdminWordMediaRouteRouteImport.update({
  id: '/api/admin/word-media',
  path: '/api/admin/word-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVerifyRouteRoute = ApiAdminVerifyRouteRouteImport.update({
  id: '/api/admin/verify',
  path: '/api/admin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTransfersRouteRoute = ApiAdminTransfersRouteRouteImport.update({
  id: '/api/admin/transfers',
  path: '/api/admin/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStepUpRouteRoute = ApiAdminStepUpRouteRouteImport.update({
  id: '/api/admin/step-up',
  path: '/api/admin/step-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentSummaryRouteRoute =
  ApiAdminContentSummaryRouteRouteImport.update({
    id: '/api/admin/content-summary',
    path: '/api/admin/content-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminContentAuditRouteRoute =
  ApiAdminContentAuditRouteRouteImport.update({
    id: '/api/admin/content-audit',
    path: '/api/admin/content-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAlbumsRouteRoute = ApiAdminAlbumsRouteRouteImport.update({
  id: '/api/admin/albums',
  path: '/api/admin/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordsShareVerifyRouteRoute =
  ApiWordsShareVerifyRouteRouteImport.update({
    id: '/share/verify',
    path: '/share/verify',
    getParentRoute: () => ApiWordsRouteRoute,
  } as any)
const ApiWordsSlugSharesRouteRoute = ApiWordsSlugSharesRouteRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => ApiWordsSlugRouteRoute,
} as any)
const ApiUploadWordsTargetsRouteRoute =
  ApiUploadWordsTargetsRouteRouteImport.update({
    id: '/api/upload/words/targets',
    path: '/api/upload/words/targets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadWordsPresignRouteRoute =
  ApiUploadWordsPresignRouteRouteImport.update({
    id: '/api/upload/words/presign',
    path: '/api/upload/words/presign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadWordsFinalizeRouteRoute =
  ApiUploadWordsFinalizeRouteRouteImport.update({
    id: '/api/upload/words/finalize',
    path: '/api/upload/words/finalize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadTransferPresignRouteRoute =
  ApiUploadTransferPresignRouteRouteImport.update({
    id: '/api/upload/transfer/presign',
    path: '/api/upload/transfer/presign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadTransferFinalizeRouteRoute =
  ApiUploadTransferFinalizeRouteRouteImport.update({
    id: '/api/upload/transfer/finalize',
    path: '/api/upload/transfer/finalize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBestDressedVotingOpenRouteRoute =
  ApiBestDressedVotingOpenRouteRouteImport.update({
    id: '/voting/open',
    path: '/voting/open',
    getParentRoute: () => ApiBestDressedRouteRoute,
  } as any)
const ApiBestDressedCodesRevokeAllRouteRoute =
  ApiBestDressedCodesRevokeAllRouteRouteImport.update({
    id: '/codes/revoke-all',
    path: '/codes/revoke-all',
    getParentRoute: () => ApiBestDressedRouteRoute,
  } as any)
const ApiBestDressedCodesMintBatchRouteRoute =
  ApiBestDressedCodesMintBatchRouteRouteImport.update({
    id: '/codes/mint-batch',
    path: '/codes/mint-batch',
    getParentRoute: () => ApiBestDressedRouteRoute,
  } as any)
const ApiBestDressedCodesMintRouteRoute =
  ApiBestDressedCodesMintRouteRouteImport.update({
    id: '/codes/mint',
    path: '/codes/mint',
    getParentRoute: () => ApiBestDressedRouteRoute,
  } as any)
const ApiAdminWordSharesCleanupRouteRoute =
  ApiAdminWordSharesCleanupRouteRouteImport.update({
    id: '/cleanup',
    path: '/cleanup',
    getParentRoute: () => ApiAdminWordSharesRouteRoute,
  } as any)
const ApiAdminWordMediaOrphansRouteRoute =
  ApiAdminWordMediaOrphansRouteRouteImport.update({
    id: '/orphans',
    path: '/orphans',
    getParentRoute: () => ApiAdminWordMediaRouteRoute,
  } as any)
const ApiAdminTransfersProcessMediaRouteRoute =
  ApiAdminTransfersProcessMediaRouteRouteImport.update({
    id: '/process-media',
    path: '/process-media',
    getParentRoute: () => ApiAdminTransfersRouteRoute,
  } as any)
const ApiAdminTransfersNukeRouteRoute =
  ApiAdminTransfersNukeRouteRouteImport.update({
    id: '/nuke',
    path: '/nuke',
    getParentRoute: () => ApiAdminTransfersRouteRoute,
  } as any)
const ApiAdminTransfersCleanupRouteRoute =
  ApiAdminTransfersCleanupRouteRouteImport.update({
    id: '/cleanup',
    path: '/cleanup',
    getParentRoute: () => ApiAdminTransfersRouteRoute,
  } as any)
const ApiAdminTransfersIdRouteRoute =
  ApiAdminTransfersIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAdminTransfersRouteRoute,
  } as any)
const ApiAdminTokensSessionsRouteRoute =
  ApiAdminTokensSessionsRouteRouteImport.update({
    id: '/api/admin/tokens/sessions',
    path: '/api/admin/tokens/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTokensRevokeRouteRoute =
  ApiAdminTokensRevokeRouteRouteImport.update({
    id: '/api/admin/tokens/revoke',
    path: '/api/admin/tokens/revoke',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminGuestsRemoveRouteRoute =
  ApiAdminGuestsRemoveRouteRouteImport.update({
    id: '/api/admin/guests/remove',
    path: '/api/admin/guests/remove',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminGuestsImportRouteRoute =
  ApiAdminGuestsImportRouteRouteImport.update({
    id: '/api/admin/guests/import',
    path: '/api/admin/guests/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminGuestsBootstrapRouteRoute =
  ApiAdminGuestsBootstrapRouteRouteImport.update({
    id: '/api/admin/guests/bootstrap',
    path: '/api/admin/guests/bootstrap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminGuestsAddRouteRoute = ApiAdminGuestsAddRouteRouteImport.update({
  id: '/api/admin/guests/add',
  path: '/api/admin/guests/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAlbumsSlugRouteRoute = ApiAdminAlbumsSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiAdminAlbumsRouteRoute,
} as any)
const ApiWordsSlugSharesIdRouteRoute =
  ApiWordsSlugSharesIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiWordsSlugSharesRouteRoute,
  } as any)
const ApiUploadTransferAppendPresignRouteRoute =
  ApiUploadTransferAppendPresignRouteRouteImport.update({
    id: '/api/upload/transfer/append/presign',
    path: '/api/upload/transfer/append/presign',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadTransferAppendFinalizeRouteRoute =
  ApiUploadTransferAppendFinalizeRouteRouteImport.update({
    id: '/api/upload/transfer/append/finalize',
    path: '/api/upload/transfer/append/finalize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTransfersIdFilesFileIdRouteRoute =
  ApiTransfersIdFilesFileIdRouteRouteImport.update({
    id: '/files/$fileId',
    path: '/files/$fileId',
    getParentRoute: () => ApiTransfersIdRouteRoute,
  } as any)
const ApiAdminTokensSessionsJtiRouteRoute =
  ApiAdminTokensSessionsJtiRouteRouteImport.update({
    id: '/$jti',
    path: '/$jti',
    getParentRoute: () => ApiAdminTokensSessionsRouteRoute,
  } as any)
const ApiAdminAlbumsSlugCoverRouteRoute =
  ApiAdminAlbumsSlugCoverRouteRouteImport.update({
    id: '/cover',
    path: '/cover',
    getParentRoute: () => ApiAdminAlbumsSlugRouteRoute,
  } as any)
const ApiTransfersIdMediaFileIdVariantRouteRoute =
  ApiTransfersIdMediaFileIdVariantRouteRouteImport.update({
    id: '/media/$fileId/$variant',
    path: '/media/$fileId/$variant',
    getParentRoute: () => ApiTransfersIdRouteRoute,
  } as any)
const ApiAdminAlbumsSlugPhotosPhotoIdRouteRoute =
  ApiAdminAlbumsSlugPhotosPhotoIdRouteRouteImport.update({
    id: '/photos/$photoId',
    path: '/photos/$photoId',
    getParentRoute: () => ApiAdminAlbumsSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best-dressed': typeof BestDressedRoute
  '/exam': typeof ExamRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/font-test': typeof FontTestRoute
  '/guestlist': typeof GuestlistRoute
  '/health': typeof HealthRoute
  '/icebreaker': typeof IcebreakerRoute
  '/party': typeof PartyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/things': typeof ThingsRouteWithChildren
  '/upload': typeof UploadRoute
  '/api/best-dressed': typeof ApiBestDressedRouteRouteWithChildren
  '/api/debug': typeof ApiDebugRouteRoute
  '/api/guests': typeof ApiGuestsRouteRouteWithChildren
  '/api/health': typeof ApiHealthRouteRoute
  '/api/words': typeof ApiWordsRouteRouteWithChildren
  '/admin/editor': typeof AdminEditorRoute
  '/t/$id': typeof TIdRoute
  '/things/heads-up': typeof ThingsHeadsUpRoute
  '/things/icebreaker': typeof ThingsIcebreakerRoute
  '/vault/$slug': typeof VaultSlugRoute
  '/words/$slug': typeof WordsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/pics/': typeof PicsIndexRoute
  '/words/': typeof WordsIndexRoute
  '/api/admin/albums': typeof ApiAdminAlbumsRouteRouteWithChildren
  '/api/admin/content-audit': typeof ApiAdminContentAuditRouteRoute
  '/api/admin/content-summary': typeof ApiAdminContentSummaryRouteRoute
  '/api/admin/step-up': typeof ApiAdminStepUpRouteRoute
  '/api/admin/transfers': typeof ApiAdminTransfersRouteRouteWithChildren
  '/api/admin/verify': typeof ApiAdminVerifyRouteRoute
  '/api/admin/word-media': typeof ApiAdminWordMediaRouteRouteWithChildren
  '/api/admin/word-shares': typeof ApiAdminWordSharesRouteRouteWithChildren
  '/api/cron/cleanup-transfers': typeof ApiCronCleanupTransfersRouteRoute
  '/api/cron/cleanup-word-media-orphans': typeof ApiCronCleanupWordMediaOrphansRouteRoute
  '/api/cron/cleanup-word-shares': typeof ApiCronCleanupWordSharesRouteRoute
  '/api/cron/process-transfer-media': typeof ApiCronProcessTransferMediaRouteRoute
  '/api/download/presign': typeof ApiDownloadPresignRouteRoute
  '/api/guests/verify-staff-pin': typeof ApiGuestsVerifyStaffPinRouteRoute
  '/api/transfers/$id': typeof ApiTransfersIdRouteRouteWithChildren
  '/api/upload/verify-pin': typeof ApiUploadVerifyPinRouteRoute
  '/api/words/$slug': typeof ApiWordsSlugRouteRouteWithChildren
  '/pics/$album/$photo': typeof PicsAlbumPhotoRoute
  '/pics/$album/': typeof PicsAlbumIndexRoute
  '/api/admin/albums/$slug': typeof ApiAdminAlbumsSlugRouteRouteWithChildren
  '/api/admin/guests/add': typeof ApiAdminGuestsAddRouteRoute
  '/api/admin/guests/bootstrap': typeof ApiAdminGuestsBootstrapRouteRoute
  '/api/admin/guests/import': typeof ApiAdminGuestsImportRouteRoute
  '/api/admin/guests/remove': typeof ApiAdminGuestsRemoveRouteRoute
  '/api/admin/tokens/revoke': typeof ApiAdminTokensRevokeRouteRoute
  '/api/admin/tokens/sessions': typeof ApiAdminTokensSessionsRouteRouteWithChildren
  '/api/admin/transfers/$id': typeof ApiAdminTransfersIdRouteRoute
  '/api/admin/transfers/cleanup': typeof ApiAdminTransfersCleanupRouteRoute
  '/api/admin/transfers/nuke': typeof ApiAdminTransfersNukeRouteRoute
  '/api/admin/transfers/process-media': typeof ApiAdminTransfersProcessMediaRouteRoute
  '/api/admin/word-media/orphans': typeof ApiAdminWordMediaOrphansRouteRoute
  '/api/admin/word-shares/cleanup': typeof ApiAdminWordSharesCleanupRouteRoute
  '/api/best-dressed/codes/mint': typeof ApiBestDressedCodesMintRouteRoute
  '/api/best-dressed/codes/mint-batch': typeof ApiBestDressedCodesMintBatchRouteRoute
  '/api/best-dressed/codes/revoke-all': typeof ApiBestDressedCodesRevokeAllRouteRoute
  '/api/best-dressed/voting/open': typeof ApiBestDressedVotingOpenRouteRoute
  '/api/upload/transfer/finalize': typeof ApiUploadTransferFinalizeRouteRoute
  '/api/upload/transfer/presign': typeof ApiUploadTransferPresignRouteRoute
  '/api/upload/words/finalize': typeof ApiUploadWordsFinalizeRouteRoute
  '/api/upload/words/presign': typeof ApiUploadWordsPresignRouteRoute
  '/api/upload/words/targets': typeof ApiUploadWordsTargetsRouteRoute
  '/api/words/$slug/shares': typeof ApiWordsSlugSharesRouteRouteWithChildren
  '/api/words/share/verify': typeof ApiWordsShareVerifyRouteRoute
  '/api/admin/albums/$slug/cover': typeof ApiAdminAlbumsSlugCoverRouteRoute
  '/api/admin/tokens/sessions/$jti': typeof ApiAdminTokensSessionsJtiRouteRoute
  '/api/transfers/$id/files/$fileId': typeof ApiTransfersIdFilesFileIdRouteRoute
  '/api/upload/transfer/append/finalize': typeof ApiUploadTransferAppendFinalizeRouteRoute
  '/api/upload/transfer/append/presign': typeof ApiUploadTransferAppendPresignRouteRoute
  '/api/words/$slug/shares/$id': typeof ApiWordsSlugSharesIdRouteRoute
  '/api/admin/albums/$slug/photos/$photoId': typeof ApiAdminAlbumsSlugPhotosPhotoIdRouteRoute
  '/api/transfers/$id/media/$fileId/$variant': typeof ApiTransfersIdMediaFileIdVariantRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-dressed': typeof BestDressedRoute
  '/exam': typeof ExamRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/font-test': typeof FontTestRoute
  '/guestlist': typeof GuestlistRoute
  '/health': typeof HealthRoute
  '/icebreaker': typeof IcebreakerRoute
  '/party': typeof PartyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/things': typeof ThingsRouteWithChildren
  '/upload': typeof UploadRoute
  '/api/best-dressed': typeof ApiBestDressedRouteRouteWithChildren
  '/api/debug': typeof ApiDebugRouteRoute
  '/api/guests': typeof ApiGuestsRouteRouteWithChildren
  '/api/health': typeof ApiHealthRouteRoute
  '/api/words': typeof ApiWordsRouteRouteWithChildren
  '/admin/editor': typeof AdminEditorRoute
  '/t/$id': typeof TIdRoute
  '/things/heads-up': typeof ThingsHeadsUpRoute
  '/things/icebreaker': typeof ThingsIcebreakerRoute
  '/vault/$slug': typeof VaultSlugRoute
  '/words/$slug': typeof WordsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/pics': typeof PicsIndexRoute
  '/words': typeof WordsIndexRoute
  '/api/admin/albums': typeof ApiAdminAlbumsRouteRouteWithChildren
  '/api/admin/content-audit': typeof ApiAdminContentAuditRouteRoute
  '/api/admin/content-summary': typeof ApiAdminContentSummaryRouteRoute
  '/api/admin/step-up': typeof ApiAdminStepUpRouteRoute
  '/api/admin/transfers': typeof ApiAdminTransfersRouteRouteWithChildren
  '/api/admin/verify': typeof ApiAdminVerifyRouteRoute
  '/api/admin/word-media': typeof ApiAdminWordMediaRouteRouteWithChildren
  '/api/admin/word-shares': typeof ApiAdminWordSharesRouteRouteWithChildren
  '/api/cron/cleanup-transfers': typeof ApiCronCleanupTransfersRouteRoute
  '/api/cron/cleanup-word-media-orphans': typeof ApiCronCleanupWordMediaOrphansRouteRoute
  '/api/cron/cleanup-word-shares': typeof ApiCronCleanupWordSharesRouteRoute
  '/api/cron/process-transfer-media': typeof ApiCronProcessTransferMediaRouteRoute
  '/api/download/presign': typeof ApiDownloadPresignRouteRoute
  '/api/guests/verify-staff-pin': typeof ApiGuestsVerifyStaffPinRouteRoute
  '/api/transfers/$id': typeof ApiTransfersIdRouteRouteWithChildren
  '/api/upload/verify-pin': typeof ApiUploadVerifyPinRouteRoute
  '/api/words/$slug': typeof ApiWordsSlugRouteRouteWithChildren
  '/pics/$album/$photo': typeof PicsAlbumPhotoRoute
  '/pics/$album': typeof PicsAlbumIndexRoute
  '/api/admin/albums/$slug': typeof ApiAdminAlbumsSlugRouteRouteWithChildren
  '/api/admin/guests/add': typeof ApiAdminGuestsAddRouteRoute
  '/api/admin/guests/bootstrap': typeof ApiAdminGuestsBootstrapRouteRoute
  '/api/admin/guests/import': typeof ApiAdminGuestsImportRouteRoute
  '/api/admin/guests/remove': typeof ApiAdminGuestsRemoveRouteRoute
  '/api/admin/tokens/revoke': typeof ApiAdminTokensRevokeRouteRoute
  '/api/admin/tokens/sessions': typeof ApiAdminTokensSessionsRouteRouteWithChildren
  '/api/admin/transfers/$id': typeof ApiAdminTransfersIdRouteRoute
  '/api/admin/transfers/cleanup': typeof ApiAdminTransfersCleanupRouteRoute
  '/api/admin/transfers/nuke': typeof ApiAdminTransfersNukeRouteRoute
  '/api/admin/transfers/process-media': typeof ApiAdminTransfersProcessMediaRouteRoute
  '/api/admin/word-media/orphans': typeof ApiAdminWordMediaOrphansRouteRoute
  '/api/admin/word-shares/cleanup': typeof ApiAdminWordSharesCleanupRouteRoute
  '/api/best-dressed/codes/mint': typeof ApiBestDressedCodesMintRouteRoute
  '/api/best-dressed/codes/mint-batch': typeof ApiBestDressedCodesMintBatchRouteRoute
  '/api/best-dressed/codes/revoke-all': typeof ApiBestDressedCodesRevokeAllRouteRoute
  '/api/best-dressed/voting/open': typeof ApiBestDressedVotingOpenRouteRoute
  '/api/upload/transfer/finalize': typeof ApiUploadTransferFinalizeRouteRoute
  '/api/upload/transfer/presign': typeof ApiUploadTransferPresignRouteRoute
  '/api/upload/words/finalize': typeof ApiUploadWordsFinalizeRouteRoute
  '/api/upload/words/presign': typeof ApiUploadWordsPresignRouteRoute
  '/api/upload/words/targets': typeof ApiUploadWordsTargetsRouteRoute
  '/api/words/$slug/shares': typeof ApiWordsSlugSharesRouteRouteWithChildren
  '/api/words/share/verify': typeof ApiWordsShareVerifyRouteRoute
  '/api/admin/albums/$slug/cover': typeof ApiAdminAlbumsSlugCoverRouteRoute
  '/api/admin/tokens/sessions/$jti': typeof ApiAdminTokensSessionsJtiRouteRoute
  '/api/transfers/$id/files/$fileId': typeof ApiTransfersIdFilesFileIdRouteRoute
  '/api/upload/transfer/append/finalize': typeof ApiUploadTransferAppendFinalizeRouteRoute
  '/api/upload/transfer/append/presign': typeof ApiUploadTransferAppendPresignRouteRoute
  '/api/words/$slug/shares/$id': typeof ApiWordsSlugSharesIdRouteRoute
  '/api/admin/albums/$slug/photos/$photoId': typeof ApiAdminAlbumsSlugPhotosPhotoIdRouteRoute
  '/api/transfers/$id/media/$fileId/$variant': typeof ApiTransfersIdMediaFileIdVariantRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best-dressed': typeof BestDressedRoute
  '/exam': typeof ExamRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/font-test': typeof FontTestRoute
  '/guestlist': typeof GuestlistRoute
  '/health': typeof HealthRoute
  '/icebreaker': typeof IcebreakerRoute
  '/party': typeof PartyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/things': typeof ThingsRouteWithChildren
  '/upload': typeof UploadRoute
  '/api/best-dressed': typeof ApiBestDressedRouteRouteWithChildren
  '/api/debug': typeof ApiDebugRouteRoute
  '/api/guests': typeof ApiGuestsRouteRouteWithChildren
  '/api/health': typeof ApiHealthRouteRoute
  '/api/words': typeof ApiWordsRouteRouteWithChildren
  '/admin/editor': typeof AdminEditorRoute
  '/t/$id': typeof TIdRoute
  '/things/heads-up': typeof ThingsHeadsUpRoute
  '/things/icebreaker': typeof ThingsIcebreakerRoute
  '/vault/$slug': typeof VaultSlugRoute
  '/words/$slug': typeof WordsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/pics/': typeof PicsIndexRoute
  '/words/': typeof WordsIndexRoute
  '/api/admin/albums': typeof ApiAdminAlbumsRouteRouteWithChildren
  '/api/admin/content-audit': typeof ApiAdminContentAuditRouteRoute
  '/api/admin/content-summary': typeof ApiAdminContentSummaryRouteRoute
  '/api/admin/step-up': typeof ApiAdminStepUpRouteRoute
  '/api/admin/transfers': typeof ApiAdminTransfersRouteRouteWithChildren
  '/api/admin/verify': typeof ApiAdminVerifyRouteRoute
  '/api/admin/word-media': typeof ApiAdminWordMediaRouteRouteWithChildren
  '/api/admin/word-shares': typeof ApiAdminWordSharesRouteRouteWithChildren
  '/api/cron/cleanup-transfers': typeof ApiCronCleanupTransfersRouteRoute
  '/api/cron/cleanup-word-media-orphans': typeof ApiCronCleanupWordMediaOrphansRouteRoute
  '/api/cron/cleanup-word-shares': typeof ApiCronCleanupWordSharesRouteRoute
  '/api/cron/process-transfer-media': typeof ApiCronProcessTransferMediaRouteRoute
  '/api/download/presign': typeof ApiDownloadPresignRouteRoute
  '/api/guests/verify-staff-pin': typeof ApiGuestsVerifyStaffPinRouteRoute
  '/api/transfers/$id': typeof ApiTransfersIdRouteRouteWithChildren
  '/api/upload/verify-pin': typeof ApiUploadVerifyPinRouteRoute
  '/api/words/$slug': typeof ApiWordsSlugRouteRouteWithChildren
  '/pics/$album/$photo': typeof PicsAlbumPhotoRoute
  '/pics/$album/': typeof PicsAlbumIndexRoute
  '/api/admin/albums/$slug': typeof ApiAdminAlbumsSlugRouteRouteWithChildren
  '/api/admin/guests/add': typeof ApiAdminGuestsAddRouteRoute
  '/api/admin/guests/bootstrap': typeof ApiAdminGuestsBootstrapRouteRoute
  '/api/admin/guests/import': typeof ApiAdminGuestsImportRouteRoute
  '/api/admin/guests/remove': typeof ApiAdminGuestsRemoveRouteRoute
  '/api/admin/tokens/revoke': typeof ApiAdminTokensRevokeRouteRoute
  '/api/admin/tokens/sessions': typeof ApiAdminTokensSessionsRouteRouteWithChildren
  '/api/admin/transfers/$id': typeof ApiAdminTransfersIdRouteRoute
  '/api/admin/transfers/cleanup': typeof ApiAdminTransfersCleanupRouteRoute
  '/api/admin/transfers/nuke': typeof ApiAdminTransfersNukeRouteRoute
  '/api/admin/transfers/process-media': typeof ApiAdminTransfersProcessMediaRouteRoute
  '/api/admin/word-media/orphans': typeof ApiAdminWordMediaOrphansRouteRoute
  '/api/admin/word-shares/cleanup': typeof ApiAdminWordSharesCleanupRouteRoute
  '/api/best-dressed/codes/mint': typeof ApiBestDressedCodesMintRouteRoute
  '/api/best-dressed/codes/mint-batch': typeof ApiBestDressedCodesMintBatchRouteRoute
  '/api/best-dressed/codes/revoke-all': typeof ApiBestDressedCodesRevokeAllRouteRoute
  '/api/best-dressed/voting/open': typeof ApiBestDressedVotingOpenRouteRoute
  '/api/upload/transfer/finalize': typeof ApiUploadTransferFinalizeRouteRoute
  '/api/upload/transfer/presign': typeof ApiUploadTransferPresignRouteRoute
  '/api/upload/words/finalize': typeof ApiUploadWordsFinalizeRouteRoute
  '/api/upload/words/presign': typeof ApiUploadWordsPresignRouteRoute
  '/api/upload/words/targets': typeof ApiUploadWordsTargetsRouteRoute
  '/api/words/$slug/shares': typeof ApiWordsSlugSharesRouteRouteWithChildren
  '/api/words/share/verify': typeof ApiWordsShareVerifyRouteRoute
  '/api/admin/albums/$slug/cover': typeof ApiAdminAlbumsSlugCoverRouteRoute
  '/api/admin/tokens/sessions/$jti': typeof ApiAdminTokensSessionsJtiRouteRoute
  '/api/transfers/$id/files/$fileId': typeof ApiTransfersIdFilesFileIdRouteRoute
  '/api/upload/transfer/append/finalize': typeof ApiUploadTransferAppendFinalizeRouteRoute
  '/api/upload/transfer/append/presign': typeof ApiUploadTransferAppendPresignRouteRoute
  '/api/words/$slug/shares/$id': typeof ApiWordsSlugSharesIdRouteRoute
  '/api/admin/albums/$slug/photos/$photoId': typeof ApiAdminAlbumsSlugPhotosPhotoIdRouteRoute
  '/api/transfers/$id/media/$fileId/$variant': typeof ApiTransfersIdMediaFileIdVariantRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/best-dressed'
    | '/exam'
    | '/feed.xml'
    | '/font-test'
    | '/guestlist'
    | '/health'
    | '/icebreaker'
    | '/party'
    | '/sitemap.xml'
    | '/things'
    | '/upload'
    | '/api/best-dressed'
    | '/api/debug'
    | '/api/guests'
    | '/api/health'
    | '/api/words'
    | '/admin/editor'
    | '/t/$id'
    | '/things/heads-up'
    | '/things/icebreaker'
    | '/vault/$slug'
    | '/words/$slug'
    | '/admin/'
    | '/pics/'
    | '/words/'
    | '/api/admin/albums'
    | '/api/admin/content-audit'
    | '/api/admin/content-summary'
    | '/api/admin/step-up'
    | '/api/admin/transfers'
    | '/api/admin/verify'
    | '/api/admin/word-media'
    | '/api/admin/word-shares'
    | '/api/cron/cleanup-transfers'
    | '/api/cron/cleanup-word-media-orphans'
    | '/api/cron/cleanup-word-shares'
    | '/api/cron/process-transfer-media'
    | '/api/download/presign'
    | '/api/guests/verify-staff-pin'
    | '/api/transfers/$id'
    | '/api/upload/verify-pin'
    | '/api/words/$slug'
    | '/pics/$album/$photo'
    | '/pics/$album/'
    | '/api/admin/albums/$slug'
    | '/api/admin/guests/add'
    | '/api/admin/guests/bootstrap'
    | '/api/admin/guests/import'
    | '/api/admin/guests/remove'
    | '/api/admin/tokens/revoke'
    | '/api/admin/tokens/sessions'
    | '/api/admin/transfers/$id'
    | '/api/admin/transfers/cleanup'
    | '/api/admin/transfers/nuke'
    | '/api/admin/transfers/process-media'
    | '/api/admin/word-media/orphans'
    | '/api/admin/word-shares/cleanup'
    | '/api/best-dressed/codes/mint'
    | '/api/best-dressed/codes/mint-batch'
    | '/api/best-dressed/codes/revoke-all'
    | '/api/best-dressed/voting/open'
    | '/api/upload/transfer/finalize'
    | '/api/upload/transfer/presign'
    | '/api/upload/words/finalize'
    | '/api/upload/words/presign'
    | '/api/upload/words/targets'
    | '/api/words/$slug/shares'
    | '/api/words/share/verify'
    | '/api/admin/albums/$slug/cover'
    | '/api/admin/tokens/sessions/$jti'
    | '/api/transfers/$id/files/$fileId'
    | '/api/upload/transfer/append/finalize'
    | '/api/upload/transfer/append/presign'
    | '/api/words/$slug/shares/$id'
    | '/api/admin/albums/$slug/photos/$photoId'
    | '/api/transfers/$id/media/$fileId/$variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/best-dressed'
    | '/exam'
    | '/feed.xml'
    | '/font-test'
    | '/guestlist'
    | '/health'
    | '/icebreaker'
    | '/party'
    | '/sitemap.xml'
    | '/things'
    | '/upload'
    | '/api/best-dressed'
    | '/api/debug'
    | '/api/guests'
    | '/api/health'
    | '/api/words'
    | '/admin/editor'
    | '/t/$id'
    | '/things/heads-up'
    | '/things/icebreaker'
    | '/vault/$slug'
    | '/words/$slug'
    | '/admin'
    | '/pics'
    | '/words'
    | '/api/admin/albums'
    | '/api/admin/content-audit'
    | '/api/admin/content-summary'
    | '/api/admin/step-up'
    | '/api/admin/transfers'
    | '/api/admin/verify'
    | '/api/admin/word-media'
    | '/api/admin/word-shares'
    | '/api/cron/cleanup-transfers'
    | '/api/cron/cleanup-word-media-orphans'
    | '/api/cron/cleanup-word-shares'
    | '/api/cron/process-transfer-media'
    | '/api/download/presign'
    | '/api/guests/verify-staff-pin'
    | '/api/transfers/$id'
    | '/api/upload/verify-pin'
    | '/api/words/$slug'
    | '/pics/$album/$photo'
    | '/pics/$album'
    | '/api/admin/albums/$slug'
    | '/api/admin/guests/add'
    | '/api/admin/guests/bootstrap'
    | '/api/admin/guests/import'
    | '/api/admin/guests/remove'
    | '/api/admin/tokens/revoke'
    | '/api/admin/tokens/sessions'
    | '/api/admin/transfers/$id'
    | '/api/admin/transfers/cleanup'
    | '/api/admin/transfers/nuke'
    | '/api/admin/transfers/process-media'
    | '/api/admin/word-media/orphans'
    | '/api/admin/word-shares/cleanup'
    | '/api/best-dressed/codes/mint'
    | '/api/best-dressed/codes/mint-batch'
    | '/api/best-dressed/codes/revoke-all'
    | '/api/best-dressed/voting/open'
    | '/api/upload/transfer/finalize'
    | '/api/upload/transfer/presign'
    | '/api/upload/words/finalize'
    | '/api/upload/words/presign'
    | '/api/upload/words/targets'
    | '/api/words/$slug/shares'
    | '/api/words/share/verify'
    | '/api/admin/albums/$slug/cover'
    | '/api/admin/tokens/sessions/$jti'
    | '/api/transfers/$id/files/$fileId'
    | '/api/upload/transfer/append/finalize'
    | '/api/upload/transfer/append/presign'
    | '/api/words/$slug/shares/$id'
    | '/api/admin/albums/$slug/photos/$photoId'
    | '/api/transfers/$id/media/$fileId/$variant'
  id:
    | '__root__'
    | '/'
    | '/best-dressed'
    | '/exam'
    | '/feed.xml'
    | '/font-test'
    | '/guestlist'
    | '/health'
    | '/icebreaker'
    | '/party'
    | '/sitemap.xml'
    | '/things'
    | '/upload'
    | '/api/best-dressed'
    | '/api/debug'
    | '/api/guests'
    | '/api/health'
    | '/api/words'
    | '/admin/editor'
    | '/t/$id'
    | '/things/heads-up'
    | '/things/icebreaker'
    | '/vault/$slug'
    | '/words/$slug'
    | '/admin/'
    | '/pics/'
    | '/words/'
    | '/api/admin/albums'
    | '/api/admin/content-audit'
    | '/api/admin/content-summary'
    | '/api/admin/step-up'
    | '/api/admin/transfers'
    | '/api/admin/verify'
    | '/api/admin/word-media'
    | '/api/admin/word-shares'
    | '/api/cron/cleanup-transfers'
    | '/api/cron/cleanup-word-media-orphans'
    | '/api/cron/cleanup-word-shares'
    | '/api/cron/process-transfer-media'
    | '/api/download/presign'
    | '/api/guests/verify-staff-pin'
    | '/api/transfers/$id'
    | '/api/upload/verify-pin'
    | '/api/words/$slug'
    | '/pics/$album/$photo'
    | '/pics/$album/'
    | '/api/admin/albums/$slug'
    | '/api/admin/guests/add'
    | '/api/admin/guests/bootstrap'
    | '/api/admin/guests/import'
    | '/api/admin/guests/remove'
    | '/api/admin/tokens/revoke'
    | '/api/admin/tokens/sessions'
    | '/api/admin/transfers/$id'
    | '/api/admin/transfers/cleanup'
    | '/api/admin/transfers/nuke'
    | '/api/admin/transfers/process-media'
    | '/api/admin/word-media/orphans'
    | '/api/admin/word-shares/cleanup'
    | '/api/best-dressed/codes/mint'
    | '/api/best-dressed/codes/mint-batch'
    | '/api/best-dressed/codes/revoke-all'
    | '/api/best-dressed/voting/open'
    | '/api/upload/transfer/finalize'
    | '/api/upload/transfer/presign'
    | '/api/upload/words/finalize'
    | '/api/upload/words/presign'
    | '/api/upload/words/targets'
    | '/api/words/$slug/shares'
    | '/api/words/share/verify'
    | '/api/admin/albums/$slug/cover'
    | '/api/admin/tokens/sessions/$jti'
    | '/api/transfers/$id/files/$fileId'
    | '/api/upload/transfer/append/finalize'
    | '/api/upload/transfer/append/presign'
    | '/api/words/$slug/shares/$id'
    | '/api/admin/albums/$slug/photos/$photoId'
    | '/api/transfers/$id/media/$fileId/$variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestDressedRoute: typeof BestDressedRoute
  ExamRoute: typeof ExamRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  FontTestRoute: typeof FontTestRoute
  GuestlistRoute: typeof GuestlistRoute
  HealthRoute: typeof HealthRoute
  IcebreakerRoute: typeof IcebreakerRoute
  PartyRoute: typeof PartyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThingsRoute: typeof ThingsRouteWithChildren
  UploadRoute: typeof UploadRoute
  ApiBestDressedRouteRoute: typeof ApiBestDressedRouteRouteWithChildren
  ApiDebugRouteRoute: typeof ApiDebugRouteRoute
  ApiGuestsRouteRoute: typeof ApiGuestsRouteRouteWithChildren
  ApiHealthRouteRoute: typeof ApiHealthRouteRoute
  ApiWordsRouteRoute: typeof ApiWordsRouteRouteWithChildren
  AdminEditorRoute: typeof AdminEditorRoute
  TIdRoute: typeof TIdRoute
  VaultSlugRoute: typeof VaultSlugRoute
  WordsSlugRoute: typeof WordsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PicsIndexRoute: typeof PicsIndexRoute
  WordsIndexRoute: typeof WordsIndexRoute
  ApiAdminAlbumsRouteRoute: typeof ApiAdminAlbumsRouteRouteWithChildren
  ApiAdminContentAuditRouteRoute: typeof ApiAdminContentAuditRouteRoute
  ApiAdminContentSummaryRouteRoute: typeof ApiAdminContentSummaryRouteRoute
  ApiAdminStepUpRouteRoute: typeof ApiAdminStepUpRouteRoute
  ApiAdminTransfersRouteRoute: typeof ApiAdminTransfersRouteRouteWithChildren
  ApiAdminVerifyRouteRoute: typeof ApiAdminVerifyRouteRoute
  ApiAdminWordMediaRouteRoute: typeof ApiAdminWordMediaRouteRouteWithChildren
  ApiAdminWordSharesRouteRoute: typeof ApiAdminWordSharesRouteRouteWithChildren
  ApiCronCleanupTransfersRouteRoute: typeof ApiCronCleanupTransfersRouteRoute
  ApiCronCleanupWordMediaOrphansRouteRoute: typeof ApiCronCleanupWordMediaOrphansRouteRoute
  ApiCronCleanupWordSharesRouteRoute: typeof ApiCronCleanupWordSharesRouteRoute
  ApiCronProcessTransferMediaRouteRoute: typeof ApiCronProcessTransferMediaRouteRoute
  ApiDownloadPresignRouteRoute: typeof ApiDownloadPresignRouteRoute
  ApiTransfersIdRouteRoute: typeof ApiTransfersIdRouteRouteWithChildren
  ApiUploadVerifyPinRouteRoute: typeof ApiUploadVerifyPinRouteRoute
  PicsAlbumPhotoRoute: typeof PicsAlbumPhotoRoute
  PicsAlbumIndexRoute: typeof PicsAlbumIndexRoute
  ApiAdminGuestsAddRouteRoute: typeof ApiAdminGuestsAddRouteRoute
  ApiAdminGuestsBootstrapRouteRoute: typeof ApiAdminGuestsBootstrapRouteRoute
  ApiAdminGuestsImportRouteRoute: typeof ApiAdminGuestsImportRouteRoute
  ApiAdminGuestsRemoveRouteRoute: typeof ApiAdminGuestsRemoveRouteRoute
  ApiAdminTokensRevokeRouteRoute: typeof ApiAdminTokensRevokeRouteRoute
  ApiAdminTokensSessionsRouteRoute: typeof ApiAdminTokensSessionsRouteRouteWithChildren
  ApiUploadTransferFinalizeRouteRoute: typeof ApiUploadTransferFinalizeRouteRoute
  ApiUploadTransferPresignRouteRoute: typeof ApiUploadTransferPresignRouteRoute
  ApiUploadWordsFinalizeRouteRoute: typeof ApiUploadWordsFinalizeRouteRoute
  ApiUploadWordsPresignRouteRoute: typeof ApiUploadWordsPresignRouteRoute
  ApiUploadWordsTargetsRouteRoute: typeof ApiUploadWordsTargetsRouteRoute
  ApiUploadTransferAppendFinalizeRouteRoute: typeof ApiUploadTransferAppendFinalizeRouteRoute
  ApiUploadTransferAppendPresignRouteRoute: typeof ApiUploadTransferAppendPresignRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/things': {
      id: '/things'
      path: '/things'
      fullPath: '/things'
      preLoaderRoute: typeof ThingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icebreaker': {
      id: '/icebreaker'
      path: '/icebreaker'
      fullPath: '/icebreaker'
      preLoaderRoute: typeof IcebreakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestlist': {
      id: '/guestlist'
      path: '/guestlist'
      fullPath: '/guestlist'
      preLoaderRoute: typeof GuestlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/font-test': {
      id: '/font-test'
      path: '/font-test'
      fullPath: '/font-test'
      preLoaderRoute: typeof FontTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-dressed': {
      id: '/best-dressed'
      path: '/best-dressed'
      fullPath: '/best-dressed'
      preLoaderRoute: typeof BestDressedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/': {
      id: '/words/'
      path: '/words'
      fullPath: '/words/'
      preLoaderRoute: typeof WordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pics/': {
      id: '/pics/'
      path: '/pics'
      fullPath: '/pics/'
      preLoaderRoute: typeof PicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/$slug': {
      id: '/words/$slug'
      path: '/words/$slug'
      fullPath: '/words/$slug'
      preLoaderRoute: typeof WordsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$slug': {
      id: '/vault/$slug'
      path: '/vault/$slug'
      fullPath: '/vault/$slug'
      preLoaderRoute: typeof VaultSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/things/icebreaker': {
      id: '/things/icebreaker'
      path: '/icebreaker'
      fullPath: '/things/icebreaker'
      preLoaderRoute: typeof ThingsIcebreakerRouteImport
      parentRoute: typeof ThingsRoute
    }
    '/things/heads-up': {
      id: '/things/heads-up'
      path: '/heads-up'
      fullPath: '/things/heads-up'
      preLoaderRoute: typeof ThingsHeadsUpRouteImport
      parentRoute: typeof ThingsRoute
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor': {
      id: '/admin/editor'
      path: '/admin/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AdminEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/words': {
      id: '/api/words'
      path: '/api/words'
      fullPath: '/api/words'
      preLoaderRoute: typeof ApiWordsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guests': {
      id: '/api/guests'
      path: '/api/guests'
      fullPath: '/api/guests'
      preLoaderRoute: typeof ApiGuestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug': {
      id: '/api/debug'
      path: '/api/debug'
      fullPath: '/api/debug'
      preLoaderRoute: typeof ApiDebugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/best-dressed': {
      id: '/api/best-dressed'
      path: '/api/best-dressed'
      fullPath: '/api/best-dressed'
      preLoaderRoute: typeof ApiBestDressedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pics/$album/': {
      id: '/pics/$album/'
      path: '/pics/$album'
      fullPath: '/pics/$album/'
      preLoaderRoute: typeof PicsAlbumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pics/$album/$photo': {
      id: '/pics/$album/$photo'
      path: '/pics/$album/$photo'
      fullPath: '/pics/$album/$photo'
      preLoaderRoute: typeof PicsAlbumPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/words/$slug': {
      id: '/api/words/$slug'
      path: '/$slug'
      fullPath: '/api/words/$slug'
      preLoaderRoute: typeof ApiWordsSlugRouteRouteImport
      parentRoute: typeof ApiWordsRouteRoute
    }
    '/api/upload/verify-pin': {
      id: '/api/upload/verify-pin'
      path: '/api/upload/verify-pin'
      fullPath: '/api/upload/verify-pin'
      preLoaderRoute: typeof ApiUploadVerifyPinRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transfers/$id': {
      id: '/api/transfers/$id'
      path: '/api/transfers/$id'
      fullPath: '/api/transfers/$id'
      preLoaderRoute: typeof ApiTransfersIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guests/verify-staff-pin': {
      id: '/api/guests/verify-staff-pin'
      path: '/verify-staff-pin'
      fullPath: '/api/guests/verify-staff-pin'
      preLoaderRoute: typeof ApiGuestsVerifyStaffPinRouteRouteImport
      parentRoute: typeof ApiGuestsRouteRoute
    }
    '/api/download/presign': {
      id: '/api/download/presign'
      path: '/api/download/presign'
      fullPath: '/api/download/presign'
      preLoaderRoute: typeof ApiDownloadPresignRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/process-transfer-media': {
      id: '/api/cron/process-transfer-media'
      path: '/api/cron/process-transfer-media'
      fullPath: '/api/cron/process-transfer-media'
      preLoaderRoute: typeof ApiCronProcessTransferMediaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cleanup-word-shares': {
      id: '/api/cron/cleanup-word-shares'
      path: '/api/cron/cleanup-word-shares'
      fullPath: '/api/cron/cleanup-word-shares'
      preLoaderRoute: typeof ApiCronCleanupWordSharesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cleanup-word-media-orphans': {
      id: '/api/cron/cleanup-word-media-orphans'
      path: '/api/cron/cleanup-word-media-orphans'
      fullPath: '/api/cron/cleanup-word-media-orphans'
      preLoaderRoute: typeof ApiCronCleanupWordMediaOrphansRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/cleanup-transfers': {
      id: '/api/cron/cleanup-transfers'
      path: '/api/cron/cleanup-transfers'
      fullPath: '/api/cron/cleanup-transfers'
      preLoaderRoute: typeof ApiCronCleanupTransfersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/word-shares': {
      id: '/api/admin/word-shares'
      path: '/api/admin/word-shares'
      fullPath: '/api/admin/word-shares'
      preLoaderRoute: typeof ApiAdminWordSharesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/word-media': {
      id: '/api/admin/word-media'
      path: '/api/admin/word-media'
      fullPath: '/api/admin/word-media'
      preLoaderRoute: typeof ApiAdminWordMediaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verify': {
      id: '/api/admin/verify'
      path: '/api/admin/verify'
      fullPath: '/api/admin/verify'
      preLoaderRoute: typeof ApiAdminVerifyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/transfers': {
      id: '/api/admin/transfers'
      path: '/api/admin/transfers'
      fullPath: '/api/admin/transfers'
      preLoaderRoute: typeof ApiAdminTransfersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/step-up': {
      id: '/api/admin/step-up'
      path: '/api/admin/step-up'
      fullPath: '/api/admin/step-up'
      preLoaderRoute: typeof ApiAdminStepUpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content-summary': {
      id: '/api/admin/content-summary'
      path: '/api/admin/content-summary'
      fullPath: '/api/admin/content-summary'
      preLoaderRoute: typeof ApiAdminContentSummaryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content-audit': {
      id: '/api/admin/content-audit'
      path: '/api/admin/content-audit'
      fullPath: '/api/admin/content-audit'
      preLoaderRoute: typeof ApiAdminContentAuditRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/albums': {
      id: '/api/admin/albums'
      path: '/api/admin/albums'
      fullPath: '/api/admin/albums'
      preLoaderRoute: typeof ApiAdminAlbumsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/words/share/verify': {
      id: '/api/words/share/verify'
      path: '/share/verify'
      fullPath: '/api/words/share/verify'
      preLoaderRoute: typeof ApiWordsShareVerifyRouteRouteImport
      parentRoute: typeof ApiWordsRouteRoute
    }
    '/api/words/$slug/shares': {
      id: '/api/words/$slug/shares'
      path: '/shares'
      fullPath: '/api/words/$slug/shares'
      preLoaderRoute: typeof ApiWordsSlugSharesRouteRouteImport
      parentRoute: typeof ApiWordsSlugRouteRoute
    }
    '/api/upload/words/targets': {
      id: '/api/upload/words/targets'
      path: '/api/upload/words/targets'
      fullPath: '/api/upload/words/targets'
      preLoaderRoute: typeof ApiUploadWordsTargetsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/words/presign': {
      id: '/api/upload/words/presign'
      path: '/api/upload/words/presign'
      fullPath: '/api/upload/words/presign'
      preLoaderRoute: typeof ApiUploadWordsPresignRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/words/finalize': {
      id: '/api/upload/words/finalize'
      path: '/api/upload/words/finalize'
      fullPath: '/api/upload/words/finalize'
      preLoaderRoute: typeof ApiUploadWordsFinalizeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/transfer/presign': {
      id: '/api/upload/transfer/presign'
      path: '/api/upload/transfer/presign'
      fullPath: '/api/upload/transfer/presign'
      preLoaderRoute: typeof ApiUploadTransferPresignRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/transfer/finalize': {
      id: '/api/upload/transfer/finalize'
      path: '/api/upload/transfer/finalize'
      fullPath: '/api/upload/transfer/finalize'
      preLoaderRoute: typeof ApiUploadTransferFinalizeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/best-dressed/voting/open': {
      id: '/api/best-dressed/voting/open'
      path: '/voting/open'
      fullPath: '/api/best-dressed/voting/open'
      preLoaderRoute: typeof ApiBestDressedVotingOpenRouteRouteImport
      parentRoute: typeof ApiBestDressedRouteRoute
    }
    '/api/best-dressed/codes/revoke-all': {
      id: '/api/best-dressed/codes/revoke-all'
      path: '/codes/revoke-all'
      fullPath: '/api/best-dressed/codes/revoke-all'
      preLoaderRoute: typeof ApiBestDressedCodesRevokeAllRouteRouteImport
      parentRoute: typeof ApiBestDressedRouteRoute
    }
    '/api/best-dressed/codes/mint-batch': {
      id: '/api/best-dressed/codes/mint-batch'
      path: '/codes/mint-batch'
      fullPath: '/api/best-dressed/codes/mint-batch'
      preLoaderRoute: typeof ApiBestDressedCodesMintBatchRouteRouteImport
      parentRoute: typeof ApiBestDressedRouteRoute
    }
    '/api/best-dressed/codes/mint': {
      id: '/api/best-dressed/codes/mint'
      path: '/codes/mint'
      fullPath: '/api/best-dressed/codes/mint'
      preLoaderRoute: typeof ApiBestDressedCodesMintRouteRouteImport
      parentRoute: typeof ApiBestDressedRouteRoute
    }
    '/api/admin/word-shares/cleanup': {
      id: '/api/admin/word-shares/cleanup'
      path: '/cleanup'
      fullPath: '/api/admin/word-shares/cleanup'
      preLoaderRoute: typeof ApiAdminWordSharesCleanupRouteRouteImport
      parentRoute: typeof ApiAdminWordSharesRouteRoute
    }
    '/api/admin/word-media/orphans': {
      id: '/api/admin/word-media/orphans'
      path: '/orphans'
      fullPath: '/api/admin/word-media/orphans'
      preLoaderRoute: typeof ApiAdminWordMediaOrphansRouteRouteImport
      parentRoute: typeof ApiAdminWordMediaRouteRoute
    }
    '/api/admin/transfers/process-media': {
      id: '/api/admin/transfers/process-media'
      path: '/process-media'
      fullPath: '/api/admin/transfers/process-media'
      preLoaderRoute: typeof ApiAdminTransfersProcessMediaRouteRouteImport
      parentRoute: typeof ApiAdminTransfersRouteRoute
    }
    '/api/admin/transfers/nuke': {
      id: '/api/admin/transfers/nuke'
      path: '/nuke'
      fullPath: '/api/admin/transfers/nuke'
      preLoaderRoute: typeof ApiAdminTransfersNukeRouteRouteImport
      parentRoute: typeof ApiAdminTransfersRouteRoute
    }
    '/api/admin/transfers/cleanup': {
      id: '/api/admin/transfers/cleanup'
      path: '/cleanup'
      fullPath: '/api/admin/transfers/cleanup'
      preLoaderRoute: typeof ApiAdminTransfersCleanupRouteRouteImport
      parentRoute: typeof ApiAdminTransfersRouteRoute
    }
    '/api/admin/transfers/$id': {
      id: '/api/admin/transfers/$id'
      path: '/$id'
      fullPath: '/api/admin/transfers/$id'
      preLoaderRoute: typeof ApiAdminTransfersIdRouteRouteImport
      parentRoute: typeof ApiAdminTransfersRouteRoute
    }
    '/api/admin/tokens/sessions': {
      id: '/api/admin/tokens/sessions'
      path: '/api/admin/tokens/sessions'
      fullPath: '/api/admin/tokens/sessions'
      preLoaderRoute: typeof ApiAdminTokensSessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tokens/revoke': {
      id: '/api/admin/tokens/revoke'
      path: '/api/admin/tokens/revoke'
      fullPath: '/api/admin/tokens/revoke'
      preLoaderRoute: typeof ApiAdminTokensRevokeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/guests/remove': {
      id: '/api/admin/guests/remove'
      path: '/api/admin/guests/remove'
      fullPath: '/api/admin/guests/remove'
      preLoaderRoute: typeof ApiAdminGuestsRemoveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/guests/import': {
      id: '/api/admin/guests/import'
      path: '/api/admin/guests/import'
      fullPath: '/api/admin/guests/import'
      preLoaderRoute: typeof ApiAdminGuestsImportRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/guests/bootstrap': {
      id: '/api/admin/guests/bootstrap'
      path: '/api/admin/guests/bootstrap'
      fullPath: '/api/admin/guests/bootstrap'
      preLoaderRoute: typeof ApiAdminGuestsBootstrapRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/guests/add': {
      id: '/api/admin/guests/add'
      path: '/api/admin/guests/add'
      fullPath: '/api/admin/guests/add'
      preLoaderRoute: typeof ApiAdminGuestsAddRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/albums/$slug': {
      id: '/api/admin/albums/$slug'
      path: '/$slug'
      fullPath: '/api/admin/albums/$slug'
      preLoaderRoute: typeof ApiAdminAlbumsSlugRouteRouteImport
      parentRoute: typeof ApiAdminAlbumsRouteRoute
    }
    '/api/words/$slug/shares/$id': {
      id: '/api/words/$slug/shares/$id'
      path: '/$id'
      fullPath: '/api/words/$slug/shares/$id'
      preLoaderRoute: typeof ApiWordsSlugSharesIdRouteRouteImport
      parentRoute: typeof ApiWordsSlugSharesRouteRoute
    }
    '/api/upload/transfer/append/presign': {
      id: '/api/upload/transfer/append/presign'
      path: '/api/upload/transfer/append/presign'
      fullPath: '/api/upload/transfer/append/presign'
      preLoaderRoute: typeof ApiUploadTransferAppendPresignRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/transfer/append/finalize': {
      id: '/api/upload/transfer/append/finalize'
      path: '/api/upload/transfer/append/finalize'
      fullPath: '/api/upload/transfer/append/finalize'
      preLoaderRoute: typeof ApiUploadTransferAppendFinalizeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transfers/$id/files/$fileId': {
      id: '/api/transfers/$id/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/api/transfers/$id/files/$fileId'
      preLoaderRoute: typeof ApiTransfersIdFilesFileIdRouteRouteImport
      parentRoute: typeof ApiTransfersIdRouteRoute
    }
    '/api/admin/tokens/sessions/$jti': {
      id: '/api/admin/tokens/sessions/$jti'
      path: '/$jti'
      fullPath: '/api/admin/tokens/sessions/$jti'
      preLoaderRoute: typeof ApiAdminTokensSessionsJtiRouteRouteImport
      parentRoute: typeof ApiAdminTokensSessionsRouteRoute
    }
    '/api/admin/albums/$slug/cover': {
      id: '/api/admin/albums/$slug/cover'
      path: '/cover'
      fullPath: '/api/admin/albums/$slug/cover'
      preLoaderRoute: typeof ApiAdminAlbumsSlugCoverRouteRouteImport
      parentRoute: typeof ApiAdminAlbumsSlugRouteRoute
    }
    '/api/transfers/$id/media/$fileId/$variant': {
      id: '/api/transfers/$id/media/$fileId/$variant'
      path: '/media/$fileId/$variant'
      fullPath: '/api/transfers/$id/media/$fileId/$variant'
      preLoaderRoute: typeof ApiTransfersIdMediaFileIdVariantRouteRouteImport
      parentRoute: typeof ApiTransfersIdRouteRoute
    }
    '/api/admin/albums/$slug/photos/$photoId': {
      id: '/api/admin/albums/$slug/photos/$photoId'
      path: '/photos/$photoId'
      fullPath: '/api/admin/albums/$slug/photos/$photoId'
      preLoaderRoute: typeof ApiAdminAlbumsSlugPhotosPhotoIdRouteRouteImport
      parentRoute: typeof ApiAdminAlbumsSlugRouteRoute
    }
  }
}

interface ThingsRouteChildren {
  ThingsHeadsUpRoute: typeof ThingsHeadsUpRoute
  ThingsIcebreakerRoute: typeof ThingsIcebreakerRoute
}

const ThingsRouteChildren: ThingsRouteChildren = {
  ThingsHeadsUpRoute: ThingsHeadsUpRoute,
  ThingsIcebreakerRoute: ThingsIcebreakerRoute,
}

const ThingsRouteWithChildren =
  ThingsRoute._addFileChildren(ThingsRouteChildren)

interface ApiBestDressedRouteRouteChildren {
  ApiBestDressedCodesMintRouteRoute: typeof ApiBestDressedCodesMintRouteRoute
  ApiBestDressedCodesMintBatchRouteRoute: typeof ApiBestDressedCodesMintBatchRouteRoute
  ApiBestDressedCodesRevokeAllRouteRoute: typeof ApiBestDressedCodesRevokeAllRouteRoute
  ApiBestDressedVotingOpenRouteRoute: typeof ApiBestDressedVotingOpenRouteRoute
}

const ApiBestDressedRouteRouteChildren: ApiBestDressedRouteRouteChildren = {
  ApiBestDressedCodesMintRouteRoute: ApiBestDressedCodesMintRouteRoute,
  ApiBestDressedCodesMintBatchRouteRoute:
    ApiBestDressedCodesMintBatchRouteRoute,
  ApiBestDressedCodesRevokeAllRouteRoute:
    ApiBestDressedCodesRevokeAllRouteRoute,
  ApiBestDressedVotingOpenRouteRoute: ApiBestDressedVotingOpenRouteRoute,
}

const ApiBestDressedRouteRouteWithChildren =
  ApiBestDressedRouteRoute._addFileChildren(ApiBestDressedRouteRouteChildren)

interface ApiGuestsRouteRouteChildren {
  ApiGuestsVerifyStaffPinRouteRoute: typeof ApiGuestsVerifyStaffPinRouteRoute
}

const ApiGuestsRouteRouteChildren: ApiGuestsRouteRouteChildren = {
  ApiGuestsVerifyStaffPinRouteRoute: ApiGuestsVerifyStaffPinRouteRoute,
}

const ApiGuestsRouteRouteWithChildren = ApiGuestsRouteRoute._addFileChildren(
  ApiGuestsRouteRouteChildren,
)

interface ApiWordsSlugSharesRouteRouteChildren {
  ApiWordsSlugSharesIdRouteRoute: typeof ApiWordsSlugSharesIdRouteRoute
}

const ApiWordsSlugSharesRouteRouteChildren: ApiWordsSlugSharesRouteRouteChildren =
  {
    ApiWordsSlugSharesIdRouteRoute: ApiWordsSlugSharesIdRouteRoute,
  }

const ApiWordsSlugSharesRouteRouteWithChildren =
  ApiWordsSlugSharesRouteRoute._addFileChildren(
    ApiWordsSlugSharesRouteRouteChildren,
  )

interface ApiWordsSlugRouteRouteChildren {
  ApiWordsSlugSharesRouteRoute: typeof ApiWordsSlugSharesRouteRouteWithChildren
}

const ApiWordsSlugRouteRouteChildren: ApiWordsSlugRouteRouteChildren = {
  ApiWordsSlugSharesRouteRoute: ApiWordsSlugSharesRouteRouteWithChildren,
}

const ApiWordsSlugRouteRouteWithChildren =
  ApiWordsSlugRouteRoute._addFileChildren(ApiWordsSlugRouteRouteChildren)

interface ApiWordsRouteRouteChildren {
  ApiWordsSlugRouteRoute: typeof ApiWordsSlugRouteRouteWithChildren
  ApiWordsShareVerifyRouteRoute: typeof ApiWordsShareVerifyRouteRoute
}

const ApiWordsRouteRouteChildren: ApiWordsRouteRouteChildren = {
  ApiWordsSlugRouteRoute: ApiWordsSlugRouteRouteWithChildren,
  ApiWordsShareVerifyRouteRoute: ApiWordsShareVerifyRouteRoute,
}

const ApiWordsRouteRouteWithChildren = ApiWordsRouteRoute._addFileChildren(
  ApiWordsRouteRouteChildren,
)

interface ApiAdminAlbumsSlugRouteRouteChildren {
  ApiAdminAlbumsSlugCoverRouteRoute: typeof ApiAdminAlbumsSlugCoverRouteRoute
  ApiAdminAlbumsSlugPhotosPhotoIdRouteRoute: typeof ApiAdminAlbumsSlugPhotosPhotoIdRouteRoute
}

const ApiAdminAlbumsSlugRouteRouteChildren: ApiAdminAlbumsSlugRouteRouteChildren =
  {
    ApiAdminAlbumsSlugCoverRouteRoute: ApiAdminAlbumsSlugCoverRouteRoute,
    ApiAdminAlbumsSlugPhotosPhotoIdRouteRoute:
      ApiAdminAlbumsSlugPhotosPhotoIdRouteRoute,
  }

const ApiAdminAlbumsSlugRouteRouteWithChildren =
  ApiAdminAlbumsSlugRouteRoute._addFileChildren(
    ApiAdminAlbumsSlugRouteRouteChildren,
  )

interface ApiAdminAlbumsRouteRouteChildren {
  ApiAdminAlbumsSlugRouteRoute: typeof ApiAdminAlbumsSlugRouteRouteWithChildren
}

const ApiAdminAlbumsRouteRouteChildren: ApiAdminAlbumsRouteRouteChildren = {
  ApiAdminAlbumsSlugRouteRoute: ApiAdminAlbumsSlugRouteRouteWithChildren,
}

const ApiAdminAlbumsRouteRouteWithChildren =
  ApiAdminAlbumsRouteRoute._addFileChildren(ApiAdminAlbumsRouteRouteChildren)

interface ApiAdminTransfersRouteRouteChildren {
  ApiAdminTransfersIdRouteRoute: typeof ApiAdminTransfersIdRouteRoute
  ApiAdminTransfersCleanupRouteRoute: typeof ApiAdminTransfersCleanupRouteRoute
  ApiAdminTransfersNukeRouteRoute: typeof ApiAdminTransfersNukeRouteRoute
  ApiAdminTransfersProcessMediaRouteRoute: typeof ApiAdminTransfersProcessMediaRouteRoute
}

const ApiAdminTransfersRouteRouteChildren: ApiAdminTransfersRouteRouteChildren =
  {
    ApiAdminTransfersIdRouteRoute: ApiAdminTransfersIdRouteRoute,
    ApiAdminTransfersCleanupRouteRoute: ApiAdminTransfersCleanupRouteRoute,
    ApiAdminTransfersNukeRouteRoute: ApiAdminTransfersNukeRouteRoute,
    ApiAdminTransfersProcessMediaRouteRoute:
      ApiAdminTransfersProcessMediaRouteRoute,
  }

const ApiAdminTransfersRouteRouteWithChildren =
  ApiAdminTransfersRouteRoute._addFileChildren(
    ApiAdminTransfersRouteRouteChildren,
  )

interface ApiAdminWordMediaRouteRouteChildren {
  ApiAdminWordMediaOrphansRouteRoute: typeof ApiAdminWordMediaOrphansRouteRoute
}

const ApiAdminWordMediaRouteRouteChildren: ApiAdminWordMediaRouteRouteChildren =
  {
    ApiAdminWordMediaOrphansRouteRoute: ApiAdminWordMediaOrphansRouteRoute,
  }

const ApiAdminWordMediaRouteRouteWithChildren =
  ApiAdminWordMediaRouteRoute._addFileChildren(
    ApiAdminWordMediaRouteRouteChildren,
  )

interface ApiAdminWordSharesRouteRouteChildren {
  ApiAdminWordSharesCleanupRouteRoute: typeof ApiAdminWordSharesCleanupRouteRoute
}

const ApiAdminWordSharesRouteRouteChildren: ApiAdminWordSharesRouteRouteChildren =
  {
    ApiAdminWordSharesCleanupRouteRoute: ApiAdminWordSharesCleanupRouteRoute,
  }

const ApiAdminWordSharesRouteRouteWithChildren =
  ApiAdminWordSharesRouteRoute._addFileChildren(
    ApiAdminWordSharesRouteRouteChildren,
  )

interface ApiTransfersIdRouteRouteChildren {
  ApiTransfersIdFilesFileIdRouteRoute: typeof ApiTransfersIdFilesFileIdRouteRoute
  ApiTransfersIdMediaFileIdVariantRouteRoute: typeof ApiTransfersIdMediaFileIdVariantRouteRoute
}

const ApiTransfersIdRouteRouteChildren: ApiTransfersIdRouteRouteChildren = {
  ApiTransfersIdFilesFileIdRouteRoute: ApiTransfersIdFilesFileIdRouteRoute,
  ApiTransfersIdMediaFileIdVariantRouteRoute:
    ApiTransfersIdMediaFileIdVariantRouteRoute,
}

const ApiTransfersIdRouteRouteWithChildren =
  ApiTransfersIdRouteRoute._addFileChildren(ApiTransfersIdRouteRouteChildren)

interface ApiAdminTokensSessionsRouteRouteChildren {
  ApiAdminTokensSessionsJtiRouteRoute: typeof ApiAdminTokensSessionsJtiRouteRoute
}

const ApiAdminTokensSessionsRouteRouteChildren: ApiAdminTokensSessionsRouteRouteChildren =
  {
    ApiAdminTokensSessionsJtiRouteRoute: ApiAdminTokensSessionsJtiRouteRoute,
  }

const ApiAdminTokensSessionsRouteRouteWithChildren =
  ApiAdminTokensSessionsRouteRoute._addFileChildren(
    ApiAdminTokensSessionsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestDressedRoute: BestDressedRoute,
  ExamRoute: ExamRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  FontTestRoute: FontTestRoute,
  GuestlistRoute: GuestlistRoute,
  HealthRoute: HealthRoute,
  IcebreakerRoute: IcebreakerRoute,
  PartyRoute: PartyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThingsRoute: ThingsRouteWithChildren,
  UploadRoute: UploadRoute,
  ApiBestDressedRouteRoute: ApiBestDressedRouteRouteWithChildren,
  ApiDebugRouteRoute: ApiDebugRouteRoute,
  ApiGuestsRouteRoute: ApiGuestsRouteRouteWithChildren,
  ApiHealthRouteRoute: ApiHealthRouteRoute,
  ApiWordsRouteRoute: ApiWordsRouteRouteWithChildren,
  AdminEditorRoute: AdminEditorRoute,
  TIdRoute: TIdRoute,
  VaultSlugRoute: VaultSlugRoute,
  WordsSlugRoute: WordsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  PicsIndexRoute: PicsIndexRoute,
  WordsIndexRoute: WordsIndexRoute,
  ApiAdminAlbumsRouteRoute: ApiAdminAlbumsRouteRouteWithChildren,
  ApiAdminContentAuditRouteRoute: ApiAdminContentAuditRouteRoute,
  ApiAdminContentSummaryRouteRoute: ApiAdminContentSummaryRouteRoute,
  ApiAdminStepUpRouteRoute: ApiAdminStepUpRouteRoute,
  ApiAdminTransfersRouteRoute: ApiAdminTransfersRouteRouteWithChildren,
  ApiAdminVerifyRouteRoute: ApiAdminVerifyRouteRoute,
  ApiAdminWordMediaRouteRoute: ApiAdminWordMediaRouteRouteWithChildren,
  ApiAdminWordSharesRouteRoute: ApiAdminWordSharesRouteRouteWithChildren,
  ApiCronCleanupTransfersRouteRoute: ApiCronCleanupTransfersRouteRoute,
  ApiCronCleanupWordMediaOrphansRouteRoute:
    ApiCronCleanupWordMediaOrphansRouteRoute,
  ApiCronCleanupWordSharesRouteRoute: ApiCronCleanupWordSharesRouteRoute,
  ApiCronProcessTransferMediaRouteRoute: ApiCronProcessTransferMediaRouteRoute,
  ApiDownloadPresignRouteRoute: ApiDownloadPresignRouteRoute,
  ApiTransfersIdRouteRoute: ApiTransfersIdRouteRouteWithChildren,
  ApiUploadVerifyPinRouteRoute: ApiUploadVerifyPinRouteRoute,
  PicsAlbumPhotoRoute: PicsAlbumPhotoRoute,
  PicsAlbumIndexRoute: PicsAlbumIndexRoute,
  ApiAdminGuestsAddRouteRoute: ApiAdminGuestsAddRouteRoute,
  ApiAdminGuestsBootstrapRouteRoute: ApiAdminGuestsBootstrapRouteRoute,
  ApiAdminGuestsImportRouteRoute: ApiAdminGuestsImportRouteRoute,
  ApiAdminGuestsRemoveRouteRoute: ApiAdminGuestsRemoveRouteRoute,
  ApiAdminTokensRevokeRouteRoute: ApiAdminTokensRevokeRouteRoute,
  ApiAdminTokensSessionsRouteRoute:
    ApiAdminTokensSessionsRouteRouteWithChildren,
  ApiUploadTransferFinalizeRouteRoute: ApiUploadTransferFinalizeRouteRoute,
  ApiUploadTransferPresignRouteRoute: ApiUploadTransferPresignRouteRoute,
  ApiUploadWordsFinalizeRouteRoute: ApiUploadWordsFinalizeRouteRoute,
  ApiUploadWordsPresignRouteRoute: ApiUploadWordsPresignRouteRoute,
  ApiUploadWordsTargetsRouteRoute: ApiUploadWordsTargetsRouteRoute,
  ApiUploadTransferAppendFinalizeRouteRoute:
    ApiUploadTransferAppendFinalizeRouteRoute,
  ApiUploadTransferAppendPresignRouteRoute:
    ApiUploadTransferAppendPresignRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
